# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-21 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Pagina static', 'verbose_name_plural': 'Pagine statiche'},
        ),
    ]
