# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-20 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0003_auto_20200915_2256'),
        ('static_page', '0002_auto_20200626_1516'),
    ]

    operations = [
    ]
