# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-07-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0076_auto_20210617_1141'),
        ('static_page', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFormCompilati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, help_text='tipo di typeform (Transparenza, Autocontrollo, Fabbisogni, etc)', max_length=255, null=True)),
                ('delega', models.CharField(blank=True, help_text="questa puo esere utile quando l'utente non ha piu la delega che ha avuto quando ha compilato il typeform", max_length=255, null=True)),
                ('comitato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafica.Sede')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafica.Persona')),
            ],
            options={
                'verbose_name': 'Typeform',
                'verbose_name_plural': 'Typeformi',
            },
        ),
    ]
