# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruppi', '0004_auto_20160203_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartenenza',
            options={'permissions': (('view_appartenenza', 'Can view Appartenenza'),), 'verbose_name_plural': 'Appartenenze'},
        ),
        migrations.AlterModelOptions(
            name='gruppo',
            options={'permissions': (('view_gruppo', 'Can view Gruppo'),), 'verbose_name_plural': 'Gruppi'},
        ),
    ]
