# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0040_refactor_nome_cognome'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAutorizzazioneTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('confermata', models.BooleanField(db_index=True, default=True, verbose_name='Confermata')),
                ('ritirata', models.BooleanField(db_index=True, default=False, verbose_name='Ritirata')),
                ('protocollo_numero', models.CharField(blank=True, max_length=512, null=True, verbose_name='Numero di protocollo')),
                ('protocollo_data', models.DateField(blank=True, null=True, verbose_name='Data di presa in carico')),
                ('motivo', models.CharField(max_length=4096, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovaAutorizzazioneTest',
            fields=[
                ('baseautorizzazionetest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autorizzazioni_test.BaseAutorizzazioneTest')),
            ],
            options={
                'abstract': False,
            },
            bases=('autorizzazioni_test.baseautorizzazionetest',),
        ),
        migrations.CreateModel(
            name='NegaAutorizzazioneTest',
            fields=[
                ('baseautorizzazionetest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autorizzazioni_test.BaseAutorizzazioneTest')),
            ],
            options={
                'abstract': False,
            },
            bases=('autorizzazioni_test.baseautorizzazionetest',),
        ),
        migrations.AddField(
            model_name='baseautorizzazionetest',
            name='appartenenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizzazioni_test', to='anagrafica.Appartenenza'),
        ),
        migrations.AddField(
            model_name='baseautorizzazionetest',
            name='destinazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizzazioni_test_destinazione', to='anagrafica.Sede'),
        ),
        migrations.AddField(
            model_name='baseautorizzazionetest',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizzazioni_test', to='anagrafica.Persona'),
        ),
        migrations.AddField(
            model_name='baseautorizzazionetest',
            name='richiedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizzazioni_test_richieste_da', to='anagrafica.Persona'),
        ),
    ]
