# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0048_auto_20171021_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMailUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(help_text='Client ID per il client MailUp')),
                ('client_secret', models.UUIDField(help_text='Secret key per il client MailUp')),
                ('username', models.CharField(help_text='Username di un account MailUp', max_length=100)),
                ('password', models.CharField(help_text='Password di un account MailUp', max_length=100)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_mailup', to='anagrafica.Sede')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
