# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmailup',
            name='refresh_token',
            field=models.CharField(default='', help_text='Refresh Token', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountmailup',
            name='token',
            field=models.CharField(default='', help_text='Token', max_length=200),
            preserve_default=False,
        ),
    ]
