# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailup', '0002_auto_20171027_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmailup',
            name='console_address',
            field=models.URLField(blank=True, help_text='Indirizzo della console MailUp. Es. https://a0f8a2.emailsp.com'),
        ),
        migrations.AlterField(
            model_name='accountmailup',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Refresh Token', max_length=200),
        ),
        migrations.AlterField(
            model_name='accountmailup',
            name='token',
            field=models.CharField(blank=True, help_text='Token', max_length=200),
        ),
    ]
