stages:
  - build
  - setup
  - restore_db
  - deploy

cache:
  key: ${CI_MERGE_REQUEST_ID}
  paths:
    - .cache/pip
    - venv/

build_containers:
  stage: build
  tags:
    - staging
  before_script:
    - chown -R gitlab-runner:gitlab-runner /home/gitlab-runner
    - docker-compose -f docker-compose-staging.yml ps
  script:
    - pwd
    - docker build -t gaia:${CI_MERGE_REQUEST_ID} .
  only:
    - merge_requests

build_master_containers:
  stage: build
  tags:
    - staging
  script:
    - pwd
    - docker build -t gaia:master .
  only:
    - master

setup_pr:
  stage: setup
  tags:
    - staging
  script:
    - echo $CI_MERGE_REQUEST_ID
    - docker-compose -f docker-compose-staging.yml down -v
    - sleep 30
    - docker-compose -f docker-compose-staging.yml up -d db
  after_script:
    - docker-compose -f docker-compose-staging.yml ps
  only:
    - merge_requests

restore_db:
  stage: restore_db
  tags:
    - staging
  before_script:
    - chown -R gitlab-runner:gitlab-runner /home/gitlab-runner
  script:
    - docker-compose -f docker-compose-staging.yml stop
    - sleep 30
    - ls -alh /opt/gaia_dumps
    - docker-compose -f docker-compose-staging.yml up -d db
    - docker-compose -f docker-compose-staging.yml ps
    - sleep 30
    - docker cp /opt/gaia_dumps/smalldump "$(docker-compose ps -q db)":/tmp/smalldump
    - echo "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'jorvik';" | docker-compose -f docker-compose-staging.yml exec -T db psql -U postgres
    - docker-compose -f docker-compose-staging.yml exec -T db pg_restore -C --clean --no-acl --no-owner -j 8 -U postgres -d postgres /tmp/smalldump
    #- cat /opt/gaia_dumps/smalldump | docker-compose -f docker-compose-staging.yml exec -T db psql -U postgres -d jorvik
  only:
    - merge_requests
  allow_failure: true

fire_pr:
  stage: deploy
  tags:
    - staging
  script:
    - echo $CI_MERGE_REQUEST_ID
    - env
    - docker-compose -f docker-compose-staging.yml up -d
    - sleep 10
    - docker-compose -f docker-compose-staging.yml restart proxy
  after_script:
    - docker-compose -f docker-compose-staging.yml ps
  environment:
    name: pr$CI_MERGE_REQUEST_ID
    url: https://pr$CI_MERGE_REQUEST_ID.staging.gaia.cri.it
  only:
    - merge_requests

restore_db_master:
  stage: restore_db
  tags:
    - staging    
  before_script:
    - export CI_MERGE_REQUEST_ID=master
    - chown -R gitlab-runner:gitlab-runner /home/gitlab-runner
  script:
    - docker-compose -f docker-compose-staging.yml stop
    - sleep 30
    - ls -alh /opt/gaia_dumps
    - docker-compose -f docker-compose-staging.yml up -d db
    - docker-compose -f docker-compose-staging.yml ps
    - sleep 30
    - docker cp /opt/gaia_dumps/smalldump "$(docker-compose ps -q db)":/tmp/smalldump
    - echo "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'jorvik';" | docker-compose -f docker-compose-staging.yml exec -T db psql -U postgres
    - docker-compose -f docker-compose-staging.yml exec -T db pg_restore -C --clean --no-acl --no-owner -j 8 -U postgres -d postgres /tmp/smalldump
    #- cat /opt/gaia_dumps/smalldump | docker-compose -f docker-compose-staging.yml exec -T db psql -U postgres -d jorvik
  only:
    - master
  allow_failure: true
 
deploy_master:
  stage: setup
  tags:
    - staging
  before_script:
    - export CI_MERGE_REQUEST_ID=master
  script:    
    - docker-compose -f docker-compose-staging.yml down -v 
    - docker-compose -f docker-compose-staging.yml up -d db
    - sleep 10  
    - docker-compose -f docker-compose-staging.yml up -d
    - sleep 30
    - docker-compose -f docker-compose-staging.yml restart proxy
  environment:
    name: staging
    url: https://master.staging.gaia.cri.it
  only:
    - master

deploy_provami:
  stage: deploy
  tags:
    - staging
  before_script:
    - export CI_MERGE_REQUEST_ID=master
  script:    
    - docker-compose -f docker-compose-staging.yml -f docker-compose-provami.yml down -v
    - docker-compose -f docker-compose-staging.yml -f docker-compose-provami.yml up -d db
    - sleep 10
    - docker-compose -f docker-compose-staging.yml -f docker-compose-provami.yml up -d
    - sleep 30
    - docker-compose -f docker-compose-staging.yml -f docker-compose-provami.yml exec -T web python scramble.py --dati-di-esempio
    - docker-compose -f docker-compose-staging.yml -f docker-compose-provami.yml restart proxy
  environment:
    name: provami
    url: https://provami.gaia.cri.it
  only:
    - master
