version: '3'

services:
  db:
    container_name: provami_db
    networks:
      - "provami-network"

  web:
    image: gaia:release
    container_name: provami_web
    networks:
      - "traefik-public"
      - "provami-network"

  celery:
    image: gaia:release
    container_name: provami_celery
    networks:
      - "provami-network"

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.provami.rule=Host(`provami.gaia.cri.it`)"
      - "traefik.http.routers.provami.entrypoints=websecure"
      - "traefik.http.routers.provami.tls.certresolver=myresolver"
      - "traefik.http.routers.provami.middlewares=provamih"
      - "traefik.http.middlewares.provamih.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.provamih.headers.stspreload=true"
      - "traefik.http.middlewares.provamih.headers.stsseconds=31536000"
      - "traefik.http.middlewares.provamih.headers.isdevelopment=false"
      - "traefik.http.middlewares.provamih.headers.sslForceHost=true"
      - "traefik.http.middlewares.provamih.headers.forceSTSHeader=true"

      container_name: provami_proxy
    networks:
      - "traefik-public"
      - "provami-network"

  pdf:
    container_name: provami_pdf
    networks:
      - "provami-network"

networks:
  provami-network:
