version: '3'

services:
  db:
    image: mdillon/postgis
    volumes:
      - .:/code
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/code
      - /tmp/media:/tmp/media
    ports:
      - "8000:8000"
    links:
      - db
      - pdf
    depends_on:
      - db
      - pdf
      - redis
      - sentinel01
      - celery
    hostname: web
    shm_size: 1g
    environment:
      - "DJANGO_LIVE_TEST_SERVER_ADDRESS=web:8081-8181"
      - "REDIS_MASTER=django"
      - "REDIS_HOST=sentinel01"
      - "SKIP_DJANGO_COLLECSTATIC=1"
      - "SKIP_DJANGO_MIGRATE=1"
      - "SKIP_REQUIREMENTS_CHECK=1"
    stdin_open: true   # Make sure stdin_open is true
    tty: true   # Make sure tty is true

  celery:
    build: .
    volumes:
      - .:/code
      - /tmp/media:/tmp/media
    links:
      - db
      - redis
      - sentinel01
      - pdf
    depends_on:
      - db
      - pdf
      - redis
      - sentinel01
    environment:
      - "SKIP_DJANGO_COLLECSTATIC=1"
      - "SKIP_DJANGO_MIGRATE=1"
      - "SKIP_REQUIREMENTS_CHECK=1"
      - "REDIS_MASTER=django"
      - "REDIS_HOST=sentinel01"
      - "WAIT_HOSTS_TIMEOUT=1200"
      - "WAIT_SLEEP_INTERVAL=60"
    command: "celery worker -A jorvik -l info -Q queue_elastic,queue_monitoraggio,queue_formazione,coda_email_rischedula,coda_email_invio,queue_monitoraggio,periodic_ufficio_soci,shared_ufficio_soci -B"


  redis:
    image: 'bitnami/redis:latest'
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_MASTER_SET=django"


  sentinel01:
    image: 'bitnami/redis-sentinel:latest'
    links:
      - redis
    depends_on:
      - redis
    environment:
      - "REDIS_MASTER_HOST=redis"
      - "REDIS_MASTER_SET=django"
    ports:
      - "26379:26739"

  pdf:
    build: https://github.com/CroceRossaItaliana/gaia-dompdf.git#master
    
