version: '3'

services:

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.provami.rule=Host(`provami.gaia.cri.it`)"
      - "traefik.http.routers.provami.entrypoints=websecure"
      - "traefik.http.routers.provami.tls.certresolver=myresolver"   