version: '3'

services:
  db:
    container_name: provami_db
  web:
    image: gaia:release
    container_name: provami_web

  broker:
    container_name: provami_broker

  celery:
    image: gaia:release
    container_name: provami_celery

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.provami.rule=Host(`provami.gaia.cri.it`)"
      - "traefik.http.routers.provami.entrypoints=websecure"
      - "traefik.http.routers.provami.tls.certresolver=myresolver"
    container_name: provami_proxy

  pdf:
    container_name: provami_pdf
