# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veicoli', '0008_fix_collocazioni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparco',
            options={'permissions': (('view_autoparco', 'Can view autoparco'),), 'verbose_name_plural': 'Autoparchi'},
        ),
        migrations.AlterModelOptions(
            name='collocazione',
            options={'permissions': (('view_collocazione', 'Can view collocazione'),), 'verbose_name': 'Collocazione veicolo', 'verbose_name_plural': 'Collocazioni veicolo'},
        ),
        migrations.AlterModelOptions(
            name='fermotecnico',
            options={'permissions': (('view_fermotecnico', 'Can view fermo tecnico'),), 'verbose_name': 'Fermo tecnico', 'verbose_name_plural': 'Fermi tecnici'},
        ),
        migrations.AlterModelOptions(
            name='manutenzione',
            options={'permissions': (('view_manutenzione', 'Can view manutenzione'),), 'verbose_name': 'Intervento di Manutenzione', 'verbose_name_plural': 'Interventi di Manutenzione'},
        ),
        migrations.AlterModelOptions(
            name='rifornimento',
            options={'permissions': (('view_rifornimento', 'Can view rifornimento'),), 'verbose_name': 'Rifornimento di carburante', 'verbose_name_plural': 'Rifornimenti di carburante'},
        ),
        migrations.AlterModelOptions(
            name='segnalazione',
            options={'permissions': (('view_segnalazione', 'Can view segnalazione'),), 'verbose_name': 'Segnalazione di malfunzionamento o incidente', 'verbose_name_plural': 'Segnalazioni di malfunzionamento o incidente'},
        ),
        migrations.AlterModelOptions(
            name='veicolo',
            options={'permissions': (('view_veicolo', 'Can view veicolo'),), 'verbose_name_plural': 'Veicoli'},
        ),
    ]
