# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicoli', '0009_auto_20160906_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veicolo',
            name='alimentazione',
            field=models.CharField(choices=[('B', 'Benzina'), ('G', 'Gasolio'), ('P', 'GPL'), ('M', 'Metano'), ('E', 'Elettrica'), ('H', 'Benzina/Elettrico')], default=None, max_length=1, null=True, verbose_name='Alimentazione (P.3)'),
        ),
    ]
