# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gestione_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0004_auto_20160328_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
                ('url_documento', models.URLField(blank=True, default='', verbose_name='URL Documento')),
            ],
            options={
                'abstract': False,
            },
            bases=(gestione_file.models.InterfacciaJorvik, 'filer.file'),
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
                ('_height', models.IntegerField(blank=True, null=True)),
                ('_width', models.IntegerField(blank=True, null=True)),
                ('default_alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='default alt text')),
                ('default_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='default caption')),
                ('subject_location', models.CharField(blank=True, default='', max_length=64, verbose_name='subject location')),
                ('url_documento', models.URLField(blank=True, default='', verbose_name='URL Documento')),
            ],
            options={
                'abstract': False,
            },
            bases=(gestione_file.models.InterfacciaJorvik, 'filer.file'),
        ),
    ]
