# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from segmenti.segmenti import NOMI_SEGMENTI


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '__latest__'),
        ('anagrafica', '__latest__'),
        ('filer', '__latest__'),
        ('gestione_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSegmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=NOMI_SEGMENTI, max_length=256)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmenti', to='filer.File')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Sede')),
                ('titolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Titolo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
