# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_file', '0002_documentosegmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='downloads',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Downloads'),
        ),
    ]
