# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_file', '0005_auto_20160520_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagine',
            name='file_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gestione_file_immagine_file', serialize=False, to='filer.File'),
        ),
    ]
