# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_file', '0006_auto_20160906_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagine',
            name='file_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File'),
        ),
    ]
