# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_file', '0007_auto_20161018_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagine',
            name='file_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gestione_file_immagine_file', serialize=False, to='filer.File'),
        ),
    ]
