# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sangue', '0003_auto_20160118_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatore',
            old_name='fanotipo_rh',
            new_name='fenotipo_rh',
        ),
    ]
