# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangue', '0004_auto_20160504_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='donazione',
            name='automatica',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Automatica'),
        ),
    ]
