# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sangue', '0005_donazione_automatica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donazione',
            options={'permissions': (('view_donazione', 'Can view Donazione'),), 'verbose_name': 'Donazione di Sangue', 'verbose_name_plural': 'Donazioni di Sangue'},
        ),
    ]
