# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0011_auto_20160521_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ['anno', 'progressivo'], 'permissions': (('view_quota', 'Can view quota'),), 'verbose_name_plural': 'Quote'},
        ),
        migrations.AlterModelOptions(
            name='tesseramento',
            options={'permissions': (('view_tesseramento', 'Can view tesseramento'),), 'verbose_name': 'Tesseramento', 'verbose_name_plural': 'Tesseramenti'},
        ),
        migrations.AlterModelOptions(
            name='tesserino',
            options={'permissions': (('view_tesserino', 'Can view tesserino'),), 'verbose_name': 'Richiesta Tesserino Associativo', 'verbose_name_plural': 'Richieste Tesserino Associativo'},
        ),
        migrations.AlterField(
            model_name='tesseramento',
            name='fine_soci',
            field=models.DateField(help_text="La data indicata è inclusa nell'intervallo in cui è permesso il tesseramento", null=True, verbose_name='Data di fine per i soci'),
        ),
        migrations.AlterField(
            model_name='tesseramento',
            name='fine_soci_iv',
            field=models.DateField(help_text="La data indicata è inclusa nell'intervallo in cui è permesso il tesseramento", null=True, verbose_name='Data di fine per infermiere volontarie'),
        ),
        migrations.AlterField(
            model_name='tesseramento',
            name='inizio',
            field=models.DateField(db_index=True, default=base.utils.oggi, help_text="La data indicata è inclusa nell'intervallo in cui è permesso il tesseramento", verbose_name='Data di inizio'),
        ),
    ]
