# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0012_auto_20160906_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='riduzione',
            field=models.CharField(blank=True, choices=[('F', 'Agevolazione richiedenti asilo o rifugiati'), ('C', 'Agevolazione per donatori sangue con meno di 25 anni')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tesseramento',
            name='quota_agevolata',
            field=models.FloatField(default=1.0),
        ),
    ]
