# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0013_auto_20170201_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riduzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(help_text='Compare nelle maschere di registrazione quote', max_length=255)),
                ('quota', models.FloatField(default=1.0)),
                ('descrizione', models.CharField(help_text='Dicitira riportata sulle ricevute e nella causale della quota', max_length=500)),
            ],
            options={
                'verbose_name': 'Riduzione',
                'permissions': (('view_riduzione', 'Can view riduzione'),),
                'verbose_name_plural': 'Riduzioni',
                'ordering': ('tesseramento__anno', 'nome'),
            },
        ),
        migrations.RemoveField(
            model_name='tesseramento',
            name='quota_agevolata',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='riduzione',
        ),
        migrations.AddField(
            model_name='quota',
            name='riduzione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='ufficio_soci.Riduzione'),
        ),
        migrations.AddField(
            model_name='riduzione',
            name='tesseramento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufficio_soci.Tesseramento'),
        ),
    ]
