# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0014_auto_20170204_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='tipo',
            field=models.CharField(choices=[('Q', 'Quota Socio'), ('S', 'Ricevuta Sostenitore'), ('R', 'Ricevuta'), ('D', 'Ricevuta Donazione')], default='Q', max_length=1),
        ),
    ]
