# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0014_auto_20170204_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportElenco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(upload_to='us_elenchi/')),
                ('report_type', models.CharField(blank=True, choices=[('sag', 'Soci al giorno')], max_length=5, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
