# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-04-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0022_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesserino',
            name='comitato_altra_lingua',
            field=models.CharField(blank=True, help_text="Inserisci il nome del comitato nell'altra lingua. Es: Komitee Bozen", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tesserino',
            name='seconda_lingua',
            field=models.CharField(choices=[('ING', 'Inglese'), ('TED', 'Tedesco')], db_index=True, default='ING', max_length=3),
        ),
    ]
