# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-04-13 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufficio_soci', '0023_auto_20210412_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesserino',
            name='comitato_altra_lingua',
        ),
        migrations.RemoveField(
            model_name='tesserino',
            name='seconda_lingua',
        ),
    ]
