version: 2

jobs:

  build:

    docker:
      - image: alfioemanuele/jorvik-docker-circleci:latest

#    environment:
#      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Django tests
          command: |
            pwd
            ls
            docker-compose up -d
            docker-compose ps
            docker-compose logs web
            docker-compose run -e SKIP_DJANGO_MIGRATE=1 web python manage.py test -v 3 --parallel 1
