version: 2

jobs:

  build:
    docker:
      - image: alfioemanuele/jorvik-docker-circleci:latest

#    environment:
#      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up -d

      - run:
          name: Django tests
          command: |
            docker-compose ps
            docker-compose exec -e SKIP_DJANGO_MIGRATE=1 project_web_1 python manage.py test -v 3 --parallel 1
