version: 2

jobs:

  build:
    docker:
      - image: ubuntu:latest

#    environment:
#      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Dependencies
          command: |
            set -x
            apt-get update
            apt-get install -y curl

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up -d

      - run:
          name: Django tests
          command: |
            docker-compose exec -e SKIP_DJANGO_MIGRATE=1 web python manage.py test -v 3 --parallel 1
