# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0013_partecipazione_centrale_operativa'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='attivita',
            index_together=set([('centrale_operativa', 'sede'), ('sede', 'estensione', 'apertura', 'stato'), ('sede', 'apertura'), ('sede', 'estensione', 'apertura'), ('sede', 'estensione', 'stato'), ('sede', 'estensione'), ('estensione', 'apertura')]),
        ),
    ]
