# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0014_auto_20160311_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['sede', 'obiettivo', 'nome'], 'permissions': (('view_area', 'Can view area'),), 'verbose_name_plural': 'Aree'},
        ),
        migrations.AlterModelOptions(
            name='attivita',
            options={'ordering': ['-creazione', 'nome'], 'permissions': (('view_attivita', 'Can view attivita'),), 'verbose_name': 'Attività', 'verbose_name_plural': 'Attività'},
        ),
        migrations.AlterModelOptions(
            name='partecipazione',
            options={'ordering': ['stato', 'persona__nome', 'persona__cognome'], 'permissions': (('view_partecipazione', 'Can view partecipazione'),), 'verbose_name': 'Richiesta di partecipazione', 'verbose_name_plural': 'Richieste di partecipazione'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['inizio', 'fine', 'id'], 'permissions': (('view_turno', 'Can view turno'),), 'verbose_name_plural': 'Turni'},
        ),
    ]
