# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0015_partecipazione_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='chiusa_automaticamente',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
