# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-25 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0018_auto_20180408_1952'),
        ('attivita', '0018_negazione_automatica_vecchie'),
    ]

    operations = [
    ]
