# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0051_auto_20190403_1504'),
        ('attivita', '0019_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSonoUnBersaglio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crentro_formazione', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Persona')),
            ],
            options={
                'verbose_name_plural': 'Referenti non sono un bersaglio',
            },
        ),
    ]
