# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-04 10:04
from __future__ import unicode_literals

import attivita.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0052_auto_20190904_1004'),
        ('attivita', '0024_auto_20190429_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(db_index=True, default='Generale', max_length=256)),
                ('obiettivo', models.SmallIntegerField(db_index=True, default=1, validators=[attivita.models.valida_numero_obiettivo])),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progetti', to='anagrafica.Sede')),
            ],
            options={
                'permissions': (('view_progetto', 'Can view progetto'),),
                'verbose_name_plural': 'Progetti',
                'ordering': ['sede', 'obiettivo', 'nome'],
            },
        ),
    ]
