# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 02:54
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0002_auto_20160117_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utenza',
            name='ultimo_accesso',
        ),
        migrations.AlterField(
            model_name='utenza',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[anagrafica.validators.valida_email_personale], verbose_name='Indirizzo email'),
        ),
    ]
