# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0003_auto_20160320_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utenza',
            options={'permissions': (('view_utenza', 'Can view utenza'),), 'verbose_name_plural': 'Utenze'},
        ),
    ]
