# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0005_auto_20160912_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='utenza',
            name='richiedi_2fa',
            field=models.BooleanField(default=False, help_text="Richiedi all'utente l'attivazione di 2FA.", verbose_name='Richiedi 2FA'),
        ),
    ]
