# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0006_utenza_richiedi_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='utenza',
            name='ultima_azione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima azione'),
        ),
    ]
