# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotiziaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NotiziaTestSegmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('segmento', models.CharField(choices=[(0, 'Delegati Obiettivo II'), (1, 'Volontari con 35 anni o più'), (2, 'Volontari'), (3, 'Presidenti di Comitati Locali'), (4, 'Delegati Obiettivo III'), (5, 'Referenti di un’Attività di Area II'), (6, 'Delegati US'), (7, 'Aspiranti volontari iscritti a un corso'), (8, 'Delegati Obiettivo VI'), (9, 'Tutti i Presidenti'), (10, 'Delegati Autoparco'), (11, 'Volontari aventi un dato titolo'), (12, 'Delegati Obiettivo IV'), (13, 'Referenti di un’Attività di Area III'), (14, 'Delegati Formazione'), (15, 'Presidenti di Comitati Regionali'), (16, 'Referenti di un’Attività di Area V'), (17, 'Delegati Obiettivo I'), (18, 'Volontari da meno di un anno'), (19, 'Volontari con meno di 35 anni'), (20, 'Sostenitori CRI'), (21, 'Tutti gli utenti di Gaia'), (22, 'Delegati Obiettivo V'), (23, 'Referenti di un’Attività di Area VI'), (24, 'Volontari da più di un anno'), (25, 'Referenti di un’Attività di Area I'), (26, 'Referenti di un’Attività di Area IV')], max_length=256)),
                ('notizia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmenti', to='segmenti_test.NotiziaTest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
