from django.conf.urls import url
# from . import viste
from .viste import (aspirante_home, aspirante_sedi, aspirante_corsi,
    aspirante_corso_base_mappa, aspirante_impostazioni,
    aspirante_impostazioni_cancella, aspirante_corso_base_informazioni,
    aspirante_corso_base_iscritti, aspirante_corso_base_iscritti_cancella,
    aspirante_corso_base_iscritti_aggiungi, aspirante_corso_base_iscriviti,
    aspirante_corso_base_ritirati, aspirante_corso_base_report,
    aspirante_corso_base_report_schede, aspirante_corso_base_firme,
    aspirante_corso_base_modifica, aspirante_corso_base_attiva,
    aspirante_corso_base_termina, aspirante_corso_base_lezioni,
    aspirante_corso_base_lezioni_cancella, aspirante_corso_estensioni_modifica)


url_shortcut = 'corso-base/(?P<pk>[0-9]+)'
app_label = 'aspirante'
urlpatterns = [
    url(r'^$', aspirante_home, name='home'),
    url(r'^impostazioni/$', aspirante_impostazioni, name='settings'),
    url(r'^impostazioni/cancella/$', aspirante_impostazioni_cancella),
    url(r'^sedi/$', aspirante_sedi, name='sedi'),
    url(r'^corsi/$', aspirante_corsi, name='corsi_base'),
    url(rf'^{url_shortcut}/$', aspirante_corso_base_informazioni, name='info'),
    url(rf'^{url_shortcut}/mappa/$', aspirante_corso_base_mappa, name='map'),
    url(rf'^{url_shortcut}/firme/$', aspirante_corso_base_firme, name='firme'),
    url(rf'^{url_shortcut}/ritirati/$', aspirante_corso_base_ritirati,
        name='retired'),
    url(rf'^{url_shortcut}/report/$', aspirante_corso_base_report,
        name='report'),
    url(rf'^{url_shortcut}/report/schede/$', aspirante_corso_base_report_schede,
        name='report_schede'),
    url(rf'^{url_shortcut}/modifica/$', aspirante_corso_base_modifica,
        name='modify'),
    url(rf'^{url_shortcut}/attiva/$', aspirante_corso_base_attiva,
        name='activate'),
    url(rf'^{url_shortcut}/termina/$', aspirante_corso_base_termina,
        name='terminate'),
    url(rf'^{url_shortcut}/lezioni/$', aspirante_corso_base_lezioni,
        name='lessons'),
    url(rf'^{url_shortcut}/lezioni/(?P<lezione_pk>[0-9]+)/cancella/$',
        aspirante_corso_base_lezioni_cancella,
        name='lessons_cancel'),
    url(rf'^{url_shortcut}/iscritti/$', aspirante_corso_base_iscritti,
        name='subscribed'),
    url(rf'^{url_shortcut}/iscritti/aggiungi/$',
        aspirante_corso_base_iscritti_aggiungi,
        name='add_to_subscribed'),
    url(rf'^{url_shortcut}/iscritti/cancella/(?P<iscritto>[0-9]+)/$',
        aspirante_corso_base_iscritti_cancella,
        name='formazione_iscritti_cancella'),
    url(rf'^{url_shortcut}/iscriviti/$', aspirante_corso_base_iscriviti,
        name='subscribe'),
    url(rf'^{url_shortcut}/estensioni/$', aspirante_corso_estensioni_modifica,
        name='estensioni_modifica'),
]
