# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0036_auto_20160301_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='data_nascita',
            field=models.DateField(db_index=True, null=True, verbose_name='Data di nascita'),
        ),
    ]
