# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0040_refactor_nome_cognome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartenenza',
            options={'permissions': (('view_appartenenza', 'Can view appartenenza'),), 'verbose_name_plural': 'Appartenenze'},
        ),
        migrations.AlterModelOptions(
            name='delega',
            options={'permissions': (('view_delega', 'Can view delega'),), 'verbose_name_plural': 'Deleghe'},
        ),
        migrations.AlterModelOptions(
            name='dimissione',
            options={'permissions': (('view_dimissione', 'Can view Documento di Dimissione'),), 'verbose_name': 'Documento di Dimissione', 'verbose_name_plural': 'Documenti di Dimissione'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'permissions': (('view_documento', 'Can view documento'),), 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='estensione',
            options={'permissions': (('view_estensions', 'Can view Richiesta di estensione'),), 'verbose_name': 'Richiesta di estensione', 'verbose_name_plural': 'Richieste di estensione'},
        ),
        migrations.AlterModelOptions(
            name='fototessera',
            options={'permissions': (('view_fototessera', 'Can view fototessera'),), 'verbose_name_plural': 'Fototessere'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('view_persona', 'Can view persona'),), 'verbose_name_plural': 'Persone'},
        ),
        migrations.AlterModelOptions(
            name='riserva',
            options={'permissions': (('view_riserva', 'Can view Richiesta di riserva'),), 'verbose_name': 'Richiesta di riserva', 'verbose_name_plural': 'Richieste di riserva'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'permissions': (('view_sede', 'Can view Sede CRI'),), 'verbose_name': 'Sede CRI', 'verbose_name_plural': 'Sedi CRI'},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'permissions': (('view_telefono', 'Can view Numero di telefono'),), 'verbose_name': 'Numero di telefono', 'verbose_name_plural': 'Numeri di telefono'},
        ),
        migrations.AlterModelOptions(
            name='trasferimento',
            options={'permissions': (('view_trasferimento', 'Can view Richiesta di trasferimento'),), 'verbose_name': 'Richiesta di trasferimento', 'verbose_name_plural': 'Richieste di trasferimento'},
        ),
    ]
