# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0041_auto_20160906_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provvedimentodisciplinare',
            options={'permissions': (('view_provvedimentodisciplinare', 'Can view Provvediemto disciplinare'),), 'verbose_name': 'Provvedimento Disciplinare', 'verbose_name_plural': 'Provvedimenti Disciplinari'},
        ),
    ]
