# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 19:34
from __future__ import unicode_literals

from django.core.exceptions import MultipleObjectsReturned
from django.db import migrations
from django.db.models import Count


def update_slug(apps, schema_editor):
    Sede = apps.get_model('anagrafica', 'Sede')
    for sede in Sede.objects.values('slug').order_by('slug').annotate(duplicati=Count('slug')):
        for to_fix in Sede.objects.filter(slug=sede['slug']).order_by('-estensione'):
            to_fix.save()


def noop(apps, schema_editor):
    # Serve solo per permettere di "tornare indietro"
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0042_auto_20170127_1928'),
    ]

    operations = [
        migrations.RunPython(update_slug, noop)
    ]
