# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 19:38
from __future__ import unicode_literals

import anagrafica.models
import autoslug.fields
import base.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0043_generate_new_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=2000, populate_from=anagrafica.models.Sede.sorgente_slug, slugify=base.utils.sede_slugify, unique=True),
        ),
    ]
