# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 22:34
from __future__ import unicode_literals

from django.db import migrations, models

from anagrafica.permessi.applicazioni import PERMESSI_NOMI


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0044_auto_20170127_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delega',
            name='tipo',
            field=models.CharField(choices=PERMESSI_NOMI, db_index=True, max_length=2),
        ),
    ]
