# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0045_auto_20170219_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasferimento',
            name='massivo',
            field=models.BooleanField(default=False, help_text='Se effettuato tramite spostamento massivo da interfaccia admin'),
        ),
    ]
