# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0045_auto_20170219_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email_servizio',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Indirizzo email servizio'),
        ),
    ]
