# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-06 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0046_persona_email_servizio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='dominio_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dominio email'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email_servizio',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email di servizio'),
        ),
    ]
