# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-09-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0047_auto_20180917_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimissione',
            name='motivo',
            field=models.CharField(choices=[('VOL', 'Dimissioni Volontarie'), ('TUR', 'Mancato svolgimento turno'), ('RIS', 'Mancato rientro da riserva'), ('QUO', 'Mancato versamento quota annuale'), ('RAD', 'Radiazione da Croce Rossa Italiana'), ('SCA', 'Scadenza contratto o altro'), ('DEC', 'Decesso'), ('TRA', 'Trasformazione in volontario'), ('ALT', 'Altro')], max_length=3),
        ),
    ]
