# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0047_auto_20170623_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenenza',
            name='membro',
            field=models.CharField(choices=[('VO', 'Volontario'), ('ES', 'Volontario in Estensione'), ('OR', 'Socio Ordinario'), ('SO', 'Sostenitore'), ('DI', 'Dipendente'), ('SD', 'Soggetto Donatore')], db_index=True, default='VO', max_length=2, verbose_name='Tipo membro'),
        ),
    ]
