# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0045_refactor_nome_cognome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('view_persona', 'Can view persona'), ('transfer_persona', "Can transfer persona")), 'verbose_name_plural': 'Persone'},
        ),
    ]
