# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-09 16:21
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0047_auto_20180406_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='dominio_email',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[anagrafica.validators.valida_dominio_email], verbose_name='Dominio email'),
        ),
    ]
