# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-15 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0049_auto_20181028_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='domicilio_cap',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CAP di domicilio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio_comune',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Comune di domicilio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio_indirizzo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Indirizzo di domicilio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio_provincia',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di domicilio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio_stato',
            field=django_countries.fields.CountryField(blank=True, default='IT', max_length=2, null=True, verbose_name='Stato di domicilio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio_uguale_a_residenza',
            field=models.BooleanField(default=False, verbose_name='Domicilio uguale a residenza'),
        )
    ]
