# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0050_auto_20190115_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='expires',
            field=models.DateField(null=True),
        )
    ]
