# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0051_auto_20190130_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('I', "Carta d'identità"), ('B', 'Passaporto'), ('P', 'Patente Civile'), ('S', 'Patente CRI'), ('C', 'Codice Fiscale'), ('A', 'Altro')], db_index=True, default='I', max_length=1),
        ),
    ]
