# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-29 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0051_auto_20190403_1504'),
        ('anagrafica', '0052_auto_20190704_1023'),
    ]

    operations = [
    ]
