# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenenza',
            name='membro',
            field=models.CharField(choices=[('VO', 'Volontario'), ('ES', 'Volontario in Estensione'), ('OR', 'Socio Ordinario'), ('SO', 'Sostenitore'), ('DI', 'Dipendente'), ('VM', 'Operatore Villa Maraini')], db_index=True, default='VO', max_length=2, verbose_name='Tipo membro'),
        ),
    ]
