# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-27 22:20
from __future__ import unicode_literals

import base.utils
from django.db import migrations
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cognome',
            field=django_cryptography.fields.encrypt(base.utils.TitleCharField(db_index=True, max_length=64, verbose_name='Cognome')),
        ),
    ]
