# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provvedimentodisciplinare',
            name='tipo',
            field=models.CharField(choices=[('A', 'Ammonizione'), ('S', 'Sospensione'), ('E', 'Esplusione'), ('R', 'Radiazione')], default='A', max_length=1),
        ),
    ]
