# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-30 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_merge'),
        ('anagrafica', '0052_auto_20190904_1004'),
    ]

    operations = [
    ]
