# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-27 22:24
from __future__ import unicode_literals

import anagrafica.validators
import base.utils
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0054_auto_20191027_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codice_fiscale',
            field=django_cryptography.fields.encrypt(base.utils.UpperCaseCharField(db_index=True, max_length=16, unique=True, validators=[anagrafica.validators.valida_codice_fiscale], verbose_name='Codice Fiscale')),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio_indirizzo',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=512, null=True, verbose_name='Indirizzo di domicilio')),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio_provincia',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di domicilio')),
        ),
    ]
