# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-27 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0054_auto_20191112_1619'),
        ('anagrafica', '0054_auto_20191023_1002'),
    ]

    operations = [
    ]
