# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0056_auto_20200515_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='indirizzo_per_spedizioni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locazione_indirizzo_spedizioni', to='base.Locazione'),
        ),
        migrations.AddField(
            model_name='sede',
            name='persona_di_riferimento',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona da contattare di riferimento'),
        ),
        migrations.AddField(
            model_name='sede',
            name='persona_di_riferimento_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero telefonico della persona di riferimento'),
        ),
        migrations.AddField(
            model_name='sede',
            name='sede_operativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locazione_sede_operativa', to='base.Locazione'),
        ),
    ]
