# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0057_auto_20200519_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('inizio', models.DateTimeField(db_index=True, verbose_name='Inizio')),
                ('fine', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Fine')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome e Cognome')),
                ('tipo', models.CharField(choices=[('rc', 'Revisore dei Conti'), ('oc', 'Organo di Controllo')], max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Nominativi',
            },
        ),
    ]
