# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0058_nominativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominativo',
            name='PEC',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nominativo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='nominativo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Sede'),
        ),
        migrations.AddField(
            model_name='nominativo',
            name='telefono',
            field=models.CharField(blank=True, max_length=64, verbose_name='FAX'),
        ),
    ]
