# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0059_auto_20200521_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='sede_operativa',
        ),
        migrations.AddField(
            model_name='sede',
            name='sede_operativa',
            field=models.ManyToManyField(to='base.Locazione'),
        ),
    ]
