# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0060_auto_20200525_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominativo',
            name='telefono',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telefono'),
        ),
    ]
