# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0061_auto_20200527_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenenza',
            name='membro',
            field=models.CharField(choices=[('VO', 'Volontario'), ('ES', 'Volontario in Estensione'), ('OR', 'Socio Ordinario'), ('SO', 'Sostenitore'), ('DI', 'Dipendente'), ('VM', 'Operatore Villa Maraini'), ('SC', 'Volontario in servizio civile universale')], db_index=True, default='VO', max_length=2, verbose_name='Tipo membro'),
        ),
        migrations.AlterField(
            model_name='dimissione',
            name='motivo',
            field=models.CharField(choices=[('VOL', 'Dimissioni Volontarie'), ('TUR', 'Mancato svolgimento turno'), ('RIS', 'Mancato rientro da riserva'), ('QUO', 'Mancato versamento quota annuale'), ('RAD', 'Radiazione da Croce Rossa Italiana'), ('SCA', 'Scadenza contratto o altro'), ('DEC', 'Decesso'), ('FSC', 'Fine progetto/Interruzione servizio civile'), ('TRA', 'Trasformazione in volontario'), ('ALT', 'Altro')], max_length=3),
        ),
    ]
