# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0063_auto_20200611_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='datore_email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='datore_p_iva',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='datore_pec',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='datore_ragione_sociale',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='datore_referente',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='datore_telefono',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, null=True),
        ),
    ]
