# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0063_auto_20200611_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoreLavoroSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('ragione_sociale', models.CharField(blank=True, db_index=True, default='', max_length=25, null=True)),
                ('partita_iva', models.CharField(blank=True, db_index=True, default='', max_length=11, null=True)),
                ('telefono', models.CharField(blank=True, db_index=True, default='', max_length=10, null=True)),
                ('referente', models.CharField(blank=True, db_index=True, default='', max_length=25, null=True)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=25, null=True)),
                ('pec', models.CharField(blank=True, db_index=True, default='', max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datori di lavoro',
                'verbose_name': 'Datore di lavoro',
            },
        ),
        migrations.AlterField(
            model_name='appartenenza',
            name='membro',
            field=models.CharField(choices=[('VO', 'Volontario'), ('ES', 'Volontario in Estensione'), ('OR', 'Socio Ordinario'), ('SO', 'Sostenitore'), ('DI', 'Dipendente'), ('VM', 'Operatore Villa Maraini'), ('SC', 'Volontario in servizio civile universale')], db_index=True, default='VO', max_length=2, verbose_name='Tipo membro'),
        ),
        migrations.AlterField(
            model_name='delega',
            name='tipo',
            field=models.CharField(choices=[('PR', 'Presidente'), ('VP', 'Vice Presidente'), ('CM', 'Commissario'), ('CN', 'Consigliere'), ('CG', 'Consigliere giovane'), ('US', 'Ufficio Soci'), ('UU', 'Ufficio Soci Unità territoriali'), ('DA', "Delegato d'Area"), ('O1', 'Delegato Obiettivo I (Salute)'), ('O2', 'Delegato Obiettivo II (Sociale)'), ('O3', 'Delegato Obiettivo III (Emergenze)'), ('O4', 'Delegato Obiettivo IV (Principi)'), ('O5', 'Delegato Obiettivo V (Giovani)'), ('O6', 'Delegato Obiettivo VI (Sviluppo)'), ('RA', "Responsabile d'Area"), ('RE', 'Referente Attività'), ('RS', 'Referente Servizio SO'), ('GR', 'Referente Gruppo'), ('CO', 'Delegato Centrale Operativa'), ('SO', 'Delegato Sala Operativa'), ('RF', 'Responsabile Formazione'), ('DC', 'Direttore Corso'), ('AP', 'Responsabile Autoparco')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='dimissione',
            name='motivo',
            field=models.CharField(choices=[('VOL', 'Dimissioni Volontarie'), ('TUR', 'Mancato svolgimento turno'), ('RIS', 'Mancato rientro da riserva'), ('QUO', 'Mancato versamento quota annuale'), ('RAD', 'Radiazione da Croce Rossa Italiana'), ('SCA', 'Scadenza contratto o altro'), ('DEC', 'Decesso'), ('FSC', 'Fine progetto/Interruzione servizio civile'), ('TRA', 'Trasformazione in volontario'), ('ALT', 'Altro')], max_length=3),
        ),
    ]
