# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-02 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0064_auto_20200902_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatoreLavoroSO',
            new_name='DatoreLavoro',
        ),
    ]
