# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0065_auto_20200902_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='datorelavoro',
            name='nominativo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, null=True),
        ),
    ]
