# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-19 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0066_auto_20201113_1212'),
        ('anagrafica', '0062_auto_20201113_1059'),
    ]

    operations = [
    ]
