# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-20 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0067_merge'),
        ('anagrafica', '0063_auto_20201013_1201'),
    ]

    operations = [
    ]
