# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-24 12:23
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0069_auto_20201124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='signature',
            field=models.CharField(default=None, max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='signature',
            field=models.CharField(default=None, max_length=50, null=True, blank=True),
        )
    ]
