# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-24 12:23
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0069_auto_20201124_1223'),
    ]

    def add_signature_to_persona(apps, schema_editor):
        Persona = apps.get_model('anagrafica', 'Persona')

        for perosna in Persona.objects.all():
            perosna.signature = uuid.uuid4()
            perosna.save()

    operations = [
        migrations.AddField(
            model_name='persona',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sede',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # migrations.RunPython(add_signature_to_persona),
    ]
