# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-04-26 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0070_signature_persone'),
        ('anagrafica', '0070_auto_20210413_1143'),
    ]

    operations = [
    ]
