# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-10 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0071_merge'),
        ('anagrafica', '0071_auto_20210406_0948'),
    ]

    operations = [
    ]
