# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-06-16 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0073_auto_20210615_1530'),
        ('anagrafica', '0072_merge'),
    ]

    operations = [
    ]
