# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-08-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0079_auto_20210730_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='delega',
            name='cri_btn',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
