# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-09-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0080_delega_cri_btn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delega',
            name='cri_btn',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='CRI'),
        ),
    ]
