# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 10:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_titoli_di_studio'),
        ('anagrafica', '0040_refactor_nome_cognome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('titolo', models.CharField(db_index=True, max_length=255, verbose_name='Titolo')),
                ('corpo', ckeditor.fields.RichTextField(verbose_name='Corpo')),
                ('estratto', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Estratto')),
                ('data_inizio_pubblicazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data di inizio pubblicazione')),
                ('data_fine_pubblicazione', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data di fine pubblicazione')),
                ('visualizzazioni', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Visualizzazioni')),
                ('stato', models.CharField(choices=[('B', 'Bozza'), ('P', 'Pubblicato')], db_index=True, default='B', max_length=1, verbose_name='Stato')),
                ('autore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='anagrafica.Persona')),
            ],
            options={
                'ordering': ['-data_inizio_pubblicazione'],
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='ArticoloSegmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('A', 'Tutti gli utenti di Gaia'), ('B', 'Volontari'), ('C', 'Volontari da meno di un anno'), ('D', 'Volontari da più di un anno'), ('E', 'Volontari con meno di 35 anni'), ('F', 'Volontari con 35 anni o più'), ('G', 'Sostenitori CRI'), ('H', 'Aspiranti volontari iscritti a un corso'), ('I', 'Tutti i Presidenti'), ('J', 'Presidenti di Comitati Locali'), ('K', 'Presidenti di Comitati Regionali'), ('L', 'Delegati US'), ('M', 'Delegati Obiettivo I'), ('N', 'Delegati Obiettivo II'), ('O', 'Delegati Obiettivo III'), ('P', 'Delegati Obiettivo IV'), ('Q', 'Delegati Obiettivo V'), ('R', 'Delegati Obiettivo VI'), ('S', 'Referenti di un’Attività di Area I'), ('T', 'Referenti di un’Attività di Area II'), ('U', 'Referenti di un’Attività di Area III'), ('V', 'Referenti di un’Attività di Area IV'), ('W', 'Referenti di un’Attività di Area V'), ('X', 'Referenti di un’Attività di Area VI'), ('Y', 'Delegati Autoparco'), ('Z', 'Delegati Formazione'), ('AA', 'Volontari aventi un dato titolo')], max_length=256)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmenti', to='articoli.Articolo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Sede')),
                ('titolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Titolo')),
            ],
            options={
                'verbose_name_plural': "Segmenti dell'Articolo",
            },
        ),
    ]
