# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 17:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from segmenti.segmenti import NOMI_SEGMENTI


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_titoli_di_studio'),
        ('anagrafica', '0040_refactor_nome_cognome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('titolo', models.CharField(db_index=True, max_length=255, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('corpo', ckeditor.fields.RichTextField(verbose_name='Corpo')),
                ('estratto', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Estratto')),
                ('data_inizio_pubblicazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data di inizio pubblicazione')),
                ('data_fine_pubblicazione', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data di fine pubblicazione')),
                ('visualizzazioni', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Visualizzazioni')),
                ('stato', models.CharField(choices=[('B', 'Bozza'), ('P', 'Pubblicato')], db_index=True, default='B', max_length=1, verbose_name='Stato')),
            ],
            options={
                'ordering': ['-data_inizio_pubblicazione'],
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='ArticoloSegmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=NOMI_SEGMENTI, max_length=256)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmenti', to='articoli.Articolo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Sede')),
                ('titolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Titolo')),
            ],
            options={
                'verbose_name_plural': 'Segmenti dell\'Articolo',
            },
        ),
    ]
