# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'ordering': ['-data_inizio_pubblicazione'], 'verbose_name': 'articolo', 'verbose_name_plural': 'articoli'},
        ),
        migrations.AlterModelOptions(
            name='articolosegmento',
            options={'verbose_name': 'segmento', 'verbose_name_plural': 'segmenti'},
        ),
        migrations.AlterField(
            model_name='articolo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articolosegmento',
            name='titolo',
            field=models.ForeignKey(blank=True, help_text="Usato solo con il segmento 'Volontari aventi un dato titolo'", null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Titolo'),
        ),
    ]
