# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0002_auto_20160530_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'ordering': ['-data_inizio_pubblicazione'], 'permissions': (('view_articolo', 'Can view articolo'),), 'verbose_name': 'articolo', 'verbose_name_plural': 'articoli'},
        ),
    ]
