# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0003_auto_20160906_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolosegmento',
            options={'permissions': (('view_articolosegmento', 'Can view articolo segmento'),)},
        ),
    ]
