# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0004_auto_20160912_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolosegmento',
            options={'permissions': (('view_articolosegmento', 'Can view articolo segmento'),), 'verbose_name': 'Articolo Segmento', 'verbose_name_plural': 'Articolo Segmenti'},
        ),
    ]
