# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-04 20:45
from __future__ import unicode_literals

import anagrafica.validators
import autoslug.fields
import base.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0045_refactor_nome_cognome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('inizio', models.DateTimeField(db_index=True, verbose_name='Inizio')),
                ('fine', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Fine')),
                ('nome', models.CharField(db_index=True, default='Nuova campagna', help_text='es. Terremoto Centro Italia', max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('organizzatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagne', to='anagrafica.Sede')),
            ],
            options={
                'verbose_name_plural': 'Campagne',
                'permissions': (('view_campagna', 'Can view campagna'),),
                'verbose_name': 'Campagna',
                'ordering': ['fine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Donatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', base.utils.TitleCharField(db_index=True, max_length=64, verbose_name='Nome')),
                ('cognome', base.utils.TitleCharField(db_index=True, max_length=64, verbose_name='Cognome')),
                ('codice_fiscale', base.utils.UpperCaseCharField(db_index=True, max_length=16, unique=True, validators=[anagrafica.validators.valida_codice_fiscale], verbose_name='Codice Fiscale')),
            ],
            options={
                'verbose_name_plural': 'Campagne',
                'permissions': (('view_campagna', 'Can view campagna'),),
                'verbose_name': 'Campagna',
            },
        ),
        migrations.CreateModel(
            name='Donazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('campagna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donazioni', to='donazioni.Campagna')),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donazioni', to='donazioni.Donatore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etichetta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='es. WEB', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=100, populate_from='nome', unique_with=('comitato',))),
                ('campagne', models.ManyToManyField(related_name='etichette', to='donazioni.Campagna')),
                ('comitato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etichette_campagne', to='anagrafica.Sede')),
            ],
            options={
                'verbose_name_plural': 'Etichette',
                'permissions': (('view_etichetta', 'Can view etichetta'),),
                'verbose_name': 'Etichetta',
                'ordering': ['nome'],
            },
        ),
    ]
