# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etichetta',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Etichetta di default'),
        ),
    ]
