# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 18:23
from __future__ import unicode_literals

import anagrafica.validators
import base.utils
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0003_auto_20170613_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatore',
            name='comune_nascita',
            field=models.CharField(blank=True, max_length=64, verbose_name='Comune di Nascita'),
        ),
        migrations.AddField(
            model_name='donatore',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AddField(
            model_name='donatore',
            name='email',
            field=models.EmailField(blank=True, max_length=64, verbose_name='Indirizzo e-mail'),
        ),
        migrations.AddField(
            model_name='donatore',
            name='provincia_nascita',
            field=models.CharField(blank=True, max_length=2, verbose_name='Provincia di Nascita'),
        ),
        migrations.AddField(
            model_name='donatore',
            name='stato_nascita',
            field=django_countries.fields.CountryField(default='IT', max_length=2, verbose_name='Stato di nascita'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='codice_transazione',
            field=models.CharField(blank=True, help_text='Codice univoco che identifica la donazione', max_length=250, verbose_name='Codice Transazione'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='data',
            field=models.DateTimeField(help_text='Data donazione', null=True, verbose_name='Data donazione'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='importo',
            field=models.FloatField(default=0.0, help_text='Importo in EUR della donazione', verbose_name='Importo in EUR'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='modalita',
            field=models.CharField(blank=True, choices=[('C', 'Contanti'), ('B', 'Bancaria'), ('O', 'Online')], db_index=True, max_length=1, verbose_name='Modalità'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='ricorrente',
            field=models.BooleanField(default=False, verbose_name='Donazione ricorrente'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='codice_fiscale',
            field=base.utils.UpperCaseCharField(blank=True, max_length=16, unique=True, validators=[anagrafica.validators.valida_codice_fiscale], verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='cognome',
            field=base.utils.TitleCharField(max_length=64, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='nome',
            field=base.utils.TitleCharField(max_length=64, verbose_name='Nome'),
        ),
    ]
