# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0004_auto_20170614_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazione',
            name='codice_transazione',
            field=models.CharField(blank=True, help_text='Codice univoco che identifica la donazione', max_length=250, null=True, verbose_name='Codice Transazione'),
        ),
        migrations.AlterField(
            model_name='donazione',
            name='donatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donazioni', to='donazioni.Donatore'),
        ),
    ]
