# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-17 13:31
from __future__ import unicode_literals

import base.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0005_auto_20170616_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatore',
            name='ragione_sociale',
            field=base.utils.TitleCharField(blank=True, help_text='Inserire la ragione sociale nel caso di persona giuridica', max_length=64, verbose_name='Ragione Sociale'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='cognome',
            field=base.utils.TitleCharField(blank=True, max_length=64, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='nome',
            field=base.utils.TitleCharField(blank=True, max_length=64, verbose_name='Nome'),
        ),
    ]
