# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-17 14:33
from __future__ import unicode_literals

import anagrafica.validators
import base.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0006_auto_20170617_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatore',
            name='codice_fiscale',
            field=base.utils.UpperCaseCharField(blank=True, max_length=16, validators=[anagrafica.validators.valida_codice_fiscale], verbose_name='Codice Fiscale'),
        ),
    ]
