# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-21 12:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0008_auto_20170621_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazione',
            name='importo',
            field=models.FloatField(default=0.0, help_text='Importo in EUR della donazione', validators=[django.core.validators.MinValueValidator(0.01, "L'importo della donazione è al di sotto del minimo consentito")], verbose_name='Importo in EUR'),
        ),
    ]
