# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-01 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0011_auto_20170630_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatore',
            name='lingua',
            field=models.CharField(blank=True, choices=[('IT', 'Italiano'), ('EN', 'Inglese'), ('FR', 'Francese'), ('ES', 'Spagnolo'), ('DE', 'Tedesco'), ('PR', 'Portoghese'), ('CH', 'Cinese Mandarino'), ('AR', 'Arabo'), ('-', 'Altra lingua non presente')], max_length=2, verbose_name='Lingua'),
        ),
    ]
