# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-21 16:31
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0012_auto_20170701_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatore',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=32, validators=[anagrafica.validators.valida_partita_iva], verbose_name='Partita IVA'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='professione',
            field=models.CharField(blank=True, choices=[('STUD', 'Studente'), ('PENS', 'Pensionato'), ('IMP', 'Impiegato'), ('IMPR', 'Imprenditore'), ('LIBPROF', 'Libero Professionista'), ('PUB', 'Dipendente Pubblica Amministrazione'), ('-', 'Altra Professione')], max_length=10, verbose_name='Professione'),
        ),
    ]
