# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0013_auto_20170721_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etichetta',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='etichetta',
            name='nome',
        ),
        migrations.AlterUniqueTogether(
            name='etichetta',
            unique_together=set([('slug', 'comitato')]),
        ),
    ]
