# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0014_auto_20170807_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatore',
            name='lingua',
            field=models.CharField(blank=True, choices=[('IT', 'Italiano'), ('EN', 'Inglese'), ('FR', 'Francese'), ('ES', 'Spagnolo'), ('DE', 'Tedesco'), ('PR', 'Portoghese'), ('JA', 'Giapponese'), ('CH', 'Cinese Mandarino'), ('AR', 'Arabo'), ('OO', 'Altra lingua non presente')], max_length=2, verbose_name='Lingua'),
        ),
        migrations.AlterField(
            model_name='donatore',
            name='professione',
            field=models.CharField(blank=True, choices=[('STUD', 'Studente'), ('PENS', 'Pensionato/a'), ('IMP', 'Impiegato/a'), ('IMPR', 'Imprenditore'), ('LIBPROF', 'Libero/a Professionista'), ('PUB', 'Dipendente Pubblica Amministrazione'), ('NN', 'Altra Professione')], max_length=10, verbose_name='Professione'),
        ),
        migrations.AlterField(
            model_name='etichetta',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Questo campo può contenere lettere, numeri e trattini', max_length=100),
        ),
    ]
