# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0015_auto_20170810_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donazione',
            name='modalita',
        ),
        migrations.AddField(
            model_name='donazione',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('C', 'Contanti'), ('B', 'Bancaria'), ('O', 'Online')], db_index=True, max_length=1, verbose_name='Metodo Pagamento'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='modalita_singola_ricorrente',
            field=models.CharField(blank=True, choices=[('S', 'Singola'), ('R', 'Ricorrente')], db_index=True, max_length=1, verbose_name='Modalità'),
        ),
    ]
