# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0016_auto_20170811_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazione',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('C', 'Contanti'), ('B', 'Bancaria'), ('P', 'PayPal'), ('A', 'Ammado'), ('Z', 'Amazon')], db_index=True, max_length=1, verbose_name='Metodo Pagamento'),
        ),
    ]
