# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0017_auto_20170811_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donazione',
            name='ricorrente',
        ),
        migrations.AlterField(
            model_name='donazione',
            name='modalita_singola_ricorrente',
            field=models.CharField(blank=True, choices=[('S', 'Singola'), ('R', 'Ricorrente')], db_index=True, help_text='Definisce se una donazione è Singola/Unica o Ricorrente', max_length=1, verbose_name='Modalità'),
        ),
    ]
