# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-11 20:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0018_auto_20170811_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazione',
            name='importo',
            field=models.FloatField(default=0.0, help_text='Importo in EUR della donazione', validators=[django.core.validators.MinValueValidator(0.0, "L'importo della donazione è al di sotto del minimo consentito")], verbose_name='Importo in EUR'),
        ),
        migrations.AlterField(
            model_name='donazione',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('C', 'Contanti'), ('R', 'CRI.it'), ('B', 'Bancaria'), ('O', 'Poste'), ('P', 'PayPal'), ('A', 'Ammado'), ('Z', 'Amazon')], db_index=True, max_length=1, verbose_name='Metodo Pagamento'),
        ),
        migrations.AlterField(
            model_name='donazione',
            name='modalita_singola_ricorrente',
            field=models.CharField(blank=True, choices=[('S', 'Singola'), ('R', 'Ricorrente')], db_index=True, default='S', help_text='Definisce se una donazione è Singola/Unica o Ricorrente', max_length=1, verbose_name='Modalità'),
        ),
    ]
