# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-13 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0019_auto_20170811_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatore',
            name='periodico',
            field=models.BooleanField(default=False, verbose_name='Donatore periodico'),
        ),
        migrations.AddField(
            model_name='etichetta',
            name='donatori',
            field=models.ManyToManyField(related_name='etichette', to='donazioni.Donatore'),
        ),
    ]
