# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-13 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0020_auto_20170813_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazione',
            name='data',
            field=models.DateTimeField(db_index=True, help_text='Data donazione', null=True, verbose_name='Data donazione'),
        ),
    ]
