# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-08 18:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0021_auto_20170813_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagna',
            name='testo_email_ringraziamento',
            field=models.TextField(blank=True, help_text="Inserire il testo che sarà incluso nella mail da inviare ai donatori che hanno fornito l'indirizzo email"),
        ),
        migrations.AlterField(
            model_name='donazione',
            name='importo',
            field=models.FloatField(default=0.0, help_text='Importo in EUR della donazione', validators=[django.core.validators.MinValueValidator(0.01, "L'importo della donazione è al di sotto del minimo consentito")], verbose_name='Importo in EUR'),
        ),
    ]
