# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0022_auto_20171008_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRegistrazioneDonatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('codice', models.CharField(db_index=True, max_length=128, unique=True)),
                ('redirect', models.CharField(db_index=True, max_length=128, null=True)),
                ('valido_ore', models.IntegerField(default=48)),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='donazioni.Donatore')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Sede')),
            ],
            options={
                'permissions': (('view_token_registrazione_donatore', 'Can view token'),),
            },
        ),
    ]
