# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0048_auto_20171021_1924'),
        ('donazioni', '0023_tokenregistrazionedonatore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociazioneDonatorePersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donazioni.Donatore')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
