# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0024_associazionedonatorepersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagna',
            name='permetti_scaricamento_ricevute',
            field=models.BooleanField(default=True, help_text='Permetti lo scaricamento delle ricevute'),
        ),
        migrations.AddField(
            model_name='donazione',
            name='permetti_scaricamento_ricevute',
            field=models.BooleanField(default=True, help_text='Permetti lo scaricamento della ricevuta'),
        ),
    ]
