# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0025_auto_20171021_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associazionedonatorepersona',
            options={'permissions': (('view_associazione_donatore_persona', 'Can view associazione donatore persona'),), 'verbose_name': 'Associazione Donatore Persona', 'verbose_name_plural': 'Associazioni Donatore Persona'},
        ),
        migrations.AddField(
            model_name='donazione',
            name='email_inviata',
            field=models.BooleanField(default=False, help_text='Email di ringraziamento e notifica ricevuta inviata al donatore'),
        ),
    ]
