# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-22 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0048_auto_20171021_1924'),
        ('donazioni', '0026_auto_20171022_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeCampagnaFittizia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campagna',
            name='fittizia',
            field=models.BooleanField(default=False, help_text='Se True, campagna fittizia per gestire profili di potenziali donatori'),
        ),
        migrations.AddField(
            model_name='sedecampagnafittizia',
            name='campagna_fittizia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donazioni.Campagna'),
        ),
        migrations.AddField(
            model_name='sedecampagnafittizia',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafica.Sede'),
        ),
    ]
