# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donazioni', '0027_auto_20171022_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagna',
            name='id_lista_mailup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
