# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_locazione_provincia_breve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locazione',
            name='provincia_breve',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Provincia (breve)'),
        ),
    ]
