# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160318_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locazione',
            name='indirizzo',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Indirizzo'),
        ),
    ]
