# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20160318_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allegato',
            options={'permissions': (('view_allegato', 'Can view allegato'),), 'verbose_name_plural': 'Allegati'},
        ),
        migrations.AlterModelOptions(
            name='autorizzazione',
            options={'permissions': (('view_autorizzazione', 'Can view autorizzazione'),), 'verbose_name_plural': 'Autorizzazioni'},
        ),
        migrations.AlterModelOptions(
            name='locazione',
            options={'permissions': (('view_locazione', 'Can view locazione'),), 'verbose_name': 'Locazione Geografica', 'verbose_name_plural': 'Locazioni Geografiche'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'permissions': (('view_token', 'Can view token'),)},
        ),
    ]
