# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 12:47
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20160318_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizzazione',
            name='scadenza',
            field=models.DateTimeField(db_index=True, default=base.utils.calcola_scadenza),
        ),
    ]
