# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20161018_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizzazione',
            name='automatica',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Approvata automaticamente'),
        ),
    ]
