# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-01-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_autorizzazione_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='Separati con lo spazio', max_length=255, null=True)),
                ('css_class', models.CharField(blank=True, help_text='Separati con lo spazio', max_length=255, null=True)),
                ('style', models.CharField(blank=True, help_text='inline css styles', max_length=255, null=True)),
                ('attrs', models.CharField(blank=True, help_text='tag attributes', max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('ls', 'Left Sidebar'), ('rs', 'Right Sidebar'), ('tn', 'Top Navbar'), ('fn', 'Footer')], max_length=5, null=True)),
            ],
        )
    ]
