# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-01-09 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190109_1053'),
        ('base', '0019_auto_20181105_1714'),
    ]

    operations = [
    ]
