# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-20 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20201005_1516'),
        ('base', '0020_merge'),
    ]

    operations = [
    ]
