# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-01-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20201124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.CharField(blank=True, choices=[('PR', 'Persona'), ('VO', 'Volontario'), ('FR', 'Formazione'), ('RU', 'Rubrica'), ('CU', 'Curriculum'), ('DO', 'Donatore'), ('SI', 'Sicurezza'), ('LK', 'Link')], default='LK', max_length=20, null=True),
        ),
    ]
