# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-01-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_menu_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizzazione',
            name='mail_verifica',
            field=models.BooleanField(default=False),
        ),
    ]
