# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-10-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0007_articolosegmento_sedi_sottostanti'),
        ('base', '0026_auto_20210406_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='segmenti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articoli.ArticoloSegmento'),
        ),
    ]
