# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190329_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(blank=True, choices=[('f', 'Formazione')], max_length=3, null=True),
        ),
    ]
