# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-24 11:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='response_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
