# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyresult_response_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
