# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20191104_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anchor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
