# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_question_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='new_version',
            field=models.BooleanField(default=False),
        ),
    ]
