# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_titoli_di_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titolo',
            options={'permissions': (('view_titolo', 'Can view titolo'),), 'verbose_name_plural': 'Titoli'},
        ),
        migrations.AlterModelOptions(
            name='titolopersonale',
            options={'permissions': (('view_titolopersonale', 'Can view titolo personale'),), 'verbose_name': 'Titolo personale', 'verbose_name_plural': 'Titoli personali'},
        ),
    ]
