# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-10-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_titolo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titolo',
            name='area',
            field=models.CharField(blank=True, choices=[('atc1', 'Salute'), ('atc2', 'Sociale'), ('atc3', 'Emergenze'), ('atc4', 'Principi e valori'), ('atc5', 'Giovani'), ('atc6', 'Sviluppo')], db_index=True, max_length=5, null=True),
        ),
    ]
