# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_auto_20181022_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_reference', models.CharField(blank=True, choices=[('1', 'Salute'), ('2', 'Sociale'), ('3', 'Emergenza)'), ('4', 'Advocacy e mediazione umanitaria'), ('5', 'Giovani'), ('6', 'Sviluppo')], max_length=3, null=True, verbose_name='Unità riferimento')),
                ('propedeuticita', models.CharField(blank=True, max_length=255, null=True, verbose_name='Propedeuticità')),
            ],
            options={
                'verbose_name': 'Titolo: Propedeuticità',
                'verbose_name_plural': 'Titoli: Propedeuticità',
            },
        ),
        migrations.CreateModel(
            name='TitleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.TitleGoal')),
            ],
            options={
                'verbose_name': 'Titolo: Livello',
                'verbose_name_plural': 'Titoli: Livelli',
            },
        ),
        migrations.AlterModelOptions(
            name='titolo',
            options={'permissions': (('view_titolo', 'Can view titolo'),), 'verbose_name_plural': 'Titoli: Elenco'},
        ),
        migrations.AlterField(
            model_name='titolo',
            name='nome',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome del corso'),
        ),
        migrations.AddField(
            model_name='titolo',
            name='livello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.TitleLevel', verbose_name='Livello'),
        ),
    ]
