# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20181119_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlelevel',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='titolo',
            name='livello',
        ),
        migrations.AddField(
            model_name='titolo',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.TitleGoal', verbose_name='Obbiettivo'),
        ),
        migrations.AddField(
            model_name='titolo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='area',
            field=models.CharField(blank=True, choices=[('1', 'Salute'), ('2', 'Sociale'), ('3', 'Emergenza)'), ('4', 'Advocacy e mediazione umanitaria'), ('5', 'Giovani'), ('6', 'Sviluppo')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TitleLevel',
        ),
    ]
