# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-12-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_auto_20181130_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='expires_after',
            field=models.IntegerField(blank=True, help_text='Indicare in giorni (es: per 1 anno indicare 365)', null=True, verbose_name='Scadenza'),
        ),
    ]
