# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-12-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_titolo_expires_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='is_course_title',
            field=models.BooleanField(default=False),
        ),
    ]
