# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_titolopersonale_is_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='cdf_durata_corso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titolo',
            name='cdf_livello',
            field=models.CharField(blank=True, choices=[('1', 'I Livello'), ('2', 'II Livello'), ('3', 'III Livello'), ('4', 'IV Livello')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='titlegoal',
            name='unit_reference',
            field=models.CharField(blank=True, choices=[('1', 'Salute'), ('2', 'Sociale'), ('3', 'Emergenza'), ('4', 'Principi e Valori'), ('5', 'Giovani'), ('6', 'Sviluppo'), ('7', 'Migrazioni'), ('8', 'Cooperazioni Internazionali')], max_length=3, null=True, verbose_name='Unità riferimento'),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='area',
            field=models.CharField(blank=True, choices=[('1', 'Salute'), ('2', 'Sociale'), ('3', 'Emergenza'), ('4', 'Principi e Valori'), ('5', 'Giovani'), ('6', 'Sviluppo'), ('7', 'Migrazioni'), ('8', 'Cooperazioni Internazionali')], db_index=True, max_length=5, null=True),
        ),
    ]
