# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_auto_20190206_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
