# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '__first__'),
        ('curriculum', '0014_auto_20190524_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='corso_partecipazione',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='titolo_ottenuto', to='formazione.PartecipazioneCorsoBase'),
        ),
    ]
