# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-05 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_titolopersonale_corso_partecipazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='scheda_competenze_in_uscita',
            field=models.TextField(blank=True, null=True, verbose_name='Competenze_in_uscita'),
        ),
        migrations.AddField(
            model_name='titolo',
            name='scheda_lezioni',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titolo',
            name='scheda_obiettivi',
            field=models.TextField(blank=True, null=True, verbose_name='Obiettivi formativi'),
        ),
    ]
