# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_titolo_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='scheda_prevede_esame',
            field=models.NullBooleanField(default=True),
        ),
    ]
