# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-14 12:07
from __future__ import unicode_literals

import curriculum.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_titolo_scheda_esame_facoltativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='attestato_file',
            field=models.FileField(blank=True, null=True, upload_to=curriculum.validators.cv_attestato_file_upload_path, verbose_name='Attestato'),
        ),
        migrations.AddField(
            model_name='titolopersonale',
            name='direttore_corso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome del direttore del corso'),
        ),
        migrations.AddField(
            model_name='titolopersonale',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='tipo',
            field=models.CharField(choices=[('CP', 'Competenza Personale'), ('PP', 'Patente Civile'), ('PC', 'Patente CRI'), ('TS', 'Titolo di Studio'), ('TC', 'Qualifica CRI')], db_index=True, max_length=2),
        ),
    ]
