# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_titolo_scheda_esame_facoltativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='scheda_verifica_finale',
            field=models.TextField(blank=True, null=True, verbose_name='Tipologia di verifica finale'),
        ),
    ]
