# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_auto_20200211_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
