# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-04 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_titolopersonale_tipo_documentazione'),
        ('curriculum', '0024_titolo_moodle'),
    ]

    operations = [
    ]
