# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-07 13:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
