# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-15 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_titolo_meta'),
        ('curriculum', '0025_modalita_titoli'),
    ]

    operations = [
    ]
