# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_auto_20210218_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='argomenti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titolo',
            name='is_partnership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='titolopersonale',
            name='settore_di_riferimento',
            field=models.CharField(blank=True, choices=[('SA', 'Salute'), ('SS', 'Salute e sicurezza'), ('IS', 'inclusione sociale'), ('EM', 'Emergenza'), ('PV', 'Principi e valori'), ('GO', 'Giovani'), ('MG', 'Migrazione'), ('CI', 'Cooperazione internazionale'), ('AL', 'Altro')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='titolopersonale',
            name='tipo_altro_titolo',
            field=models.CharField(blank=True, choices=[('PT', 'Corsi in partnership con CRI'), ('AL', 'Altri tipo di corso')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='tipo',
            field=models.CharField(choices=[('CP', 'Competenza Personale'), ('PP', 'Patente Civile'), ('PC', 'Patente CRI'), ('TS', 'Titolo di Studio'), ('TC', 'Qualifica CRI'), ('AT', 'Altra Qualifica')], db_index=True, max_length=2),
        ),
    ]
