# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_auto_20210218_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='argomento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
