# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_titolopersonale_argomento'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='tipo_titolo_studio',
            field=models.CharField(blank=True, choices=[('DP', 'DIPLOMA'), ('LA', 'LAUREA')], db_index=True, max_length=2, null=True),
        ),
    ]
