# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_titolo_tipo_titolo_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='tipo_titolo_di_studio',
            field=models.CharField(blank=True, choices=[('SO', "Scuola dell'obbligo"), ('DI', 'Diploma'), ('L3', 'Laureando/a 3 anni'), ('LS', 'Laureando/a specialistica o vecchio ordinamento'), ('LS', 'Laurea 3 anni'), ('LV', 'Laurea vecchio ordinamento'), ('LS', 'Laurea specialistica'), ('SP', 'Specializzazione post-laurea'), ('MA', 'Master'), ('DT', 'Dottorato')], max_length=2, null=True),
        ),
    ]
