# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_titolopersonale_tipo_titolo_di_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='livello_linguistico_lettura',
            field=models.CharField(blank=True, choices=[('A1', 'Base A1'), ('A2', 'Elementare A2'), ('B1', 'Pre-intermedio B1'), ('B2', 'Intermedio B2'), ('C1', 'Post-intermedio C1'), ('C2', 'Avanzato C2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='titolopersonale',
            name='livello_linguistico_orale',
            field=models.CharField(blank=True, choices=[('A1', 'Base A1'), ('A2', 'Elementare A2'), ('B1', 'Pre-intermedio B1'), ('B2', 'Intermedio B2'), ('C1', 'Post-intermedio C1'), ('C2', 'Avanzato C2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='titolopersonale',
            name='livello_linguistico_scrittura',
            field=models.CharField(blank=True, choices=[('A1', 'Base A1'), ('A2', 'Elementare A2'), ('B1', 'Pre-intermedio B1'), ('B2', 'Intermedio B2'), ('C1', 'Post-intermedio C1'), ('C2', 'Avanzato C2')], max_length=2, null=True),
        ),
    ]
