# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_auto_20210315_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titolo',
            name='tipo_titolo_studio',
            field=models.CharField(blank=True, choices=[('DI', 'DIPLOMA'), ('LA', 'LAUREA')], db_index=True, max_length=2, null=True),
        ),
    ]
