# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-17 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0038_titoloprofessionale_titoloskill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitoloProfessionale',
            new_name='TitoloSpecializzazione',
        ),
    ]
