# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0039_auto_20210317_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='esperienza',
            field=models.CharField(blank=True, choices=[('I3', 'No'), ('C6', 'Si, periodo cumulativo da tre a sei mesi'), ('CA', 'Si, periodo cumulativo da sei a un anno'), ('CO', 'Si, periodo cumulativo oltre un anno')], max_length=2, null=True),
        ),
    ]
