# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_titolopersonale_esperienza'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolopersonale',
            name='codice_albo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
