# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0006_auto_20160228_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatario',
            options={'permissions': (('view_destinatario', 'Can view destinatario'),), 'verbose_name': 'Destinatario di posta', 'verbose_name_plural': 'Destinatario di posta'},
        ),
        migrations.AlterModelOptions(
            name='messaggio',
            options={'permissions': (('view_messaggio', 'Can view messaggio'),), 'verbose_name': 'Messaggio di posta', 'verbose_name_plural': 'Messaggi di posta'},
        ),
    ]
