# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0007_auto_20160906_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='invalido',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
