# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-22 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0010_posta_obsoleta_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggio',
            name='priorita',
            field=models.IntegerField(default=0),
        ),
    ]
