# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-31 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0012_messaggio_utenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggio',
            name='priorita',
            field=models.IntegerField(default=0, help_text="La priorità viene utilizzata per stabilire l'ordine nello smistamento della coda, quando c'è un errore questo valore viene incrementato"),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='utenza',
            field=models.BooleanField(default=False, help_text="Se l'utente possiede un'email differente da quella utilizzata per il login, il messaggio viene recapito ad entrambe"),
        ),
    ]
