# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-10 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0013_auto_20180331_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='errore',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
    ]
