# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0014_auto_20180410_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaggio',
            name='priorita',
        ),
        migrations.AddField(
            model_name='messaggio',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
