# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0015_auto_20180415_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='errore_codice',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, help_text="Un codice numerico che rappresenta l'errore.", null=True),
        ),
        migrations.AddField(
            model_name='messaggio',
            name='tentativi',
            field=models.IntegerField(default=0, help_text='Il numero di tentativi di invio effettuati per questo messaggio. Quando questo numero supera il massimo, non verranno effettuati nuovi tentativi.'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='errore',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Una stringa che descrive l'errore di invio, se alcuno.", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='invalido',
            field=models.BooleanField(db_index=True, default=False, help_text="Indica se il destinatario e' invalido."),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='inviato',
            field=models.BooleanField(db_index=True, default=False, help_text="Indica se l'email per questo destinatario e' stata inviata, oppure sono stati esauriti i tentativi di invio."),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='tentativo',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text="La data dell'ultimo tentativo di invio.", null=True),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='task_id',
            field=models.CharField(blank=True, default=None, help_text='ID del task Celery per lo smistamento di questo messaggio.', max_length=36, null=True),
        ),
    ]
