# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-18 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0016_auto_20180417_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='inviato',
            field=models.BooleanField(db_index=True, default=False, help_text="Indica se l'email per questo destinatario e' stata inviata,"),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='terminato',
            field=models.DateTimeField(blank=True, default=None, help_text="La data di termine dell'invio. Questa data e' impostata quando l'invio e' terminato con successo, oppure quando sono esauriti i tentativi di invio.", null=True),
        ),
    ]
