from django.conf.urls import url
from .. import viste as v


url_shortcut = 'corso-base/(?P<pk>[0-9]+)'
app_label = 'aspirante'
urlpatterns = [
    url(r'^$', v.aspirante_home, name='home'),
    url(r'^impostazioni/$', v.aspirante_impostazioni, name='settings'),
    url(r'^impostazioni/cancella/$', v.aspirante_impostazioni_cancella),
    url(r'^sedi/$', v.aspirante_sedi, name='sedi'),
    url(r'^corsi/$', v.aspirante_corsi, name='corsi_base'),
    url(r'^%s/$' % url_shortcut, v.aspirante_corso_base_informazioni,
        name='info'),
    url(r'^%s/mappa/$' % url_shortcut, v.aspirante_corso_base_mappa,
        name='map'),
    url(r'^%s/position/change' % url_shortcut, v.formazione_corso_position_change,
        name='position_change'),
    url(r'^%s/firme/$' % url_shortcut, v.aspirante_corso_base_firme,
        name='firme'),
    url(r'^%s/ritirati/$' % url_shortcut, v.aspirante_corso_base_ritirati,
        name='retired'),
    url(r'^%s/report/$' % url_shortcut, v.aspirante_corso_base_report,
        name='report'),
    url(r'^%s/report/schede/$' % url_shortcut,
        v.aspirante_corso_base_report_schede,
        name='report_schede'),
    url(r'^%s/modifica/$' % url_shortcut, v.aspirante_corso_base_modifica,
        name='modify'),
    url(r'^%s/attiva/$' % url_shortcut, v.aspirante_corso_base_attiva,
        name='activate'),
    url(r'^%s/termina/$' % url_shortcut, v.aspirante_corso_base_termina,
        name='terminate'),
    url(r'^%s/annulla/$' % url_shortcut, v.aspirante_corso_base_annulla,
        name='annulla'),
    url(r'^%s/lezioni/$' % url_shortcut, v.aspirante_corso_base_lezioni,
        name='lessons'),
    url(r'^%s/lezioni/(?P<lezione_pk>[0-9]+)/cancella/$' % url_shortcut,
        v.aspirante_corso_base_lezioni_cancella,
        name='lessons_cancel'),
    url(r'^%s/iscritti/$' % url_shortcut, v.aspirante_corso_base_iscritti,
        name='subscribed'),
    url(r'^%s/iscritti/aggiungi/$' % url_shortcut,
        v.aspirante_corso_base_iscritti_aggiungi,
        name='add_to_subscribed'),
    url(r'^%s/iscritti/cancella/(?P<iscritto>[0-9]+)/$' % url_shortcut,
        v.aspirante_corso_base_iscritti_cancella,
        name='formazione_iscritti_cancella'),
    url(r'^%s/iscriviti/$' % url_shortcut, v.aspirante_corso_base_iscriviti,
        name='subscribe'),
    url(r'^%s/estensioni/$' % url_shortcut, v.aspirante_corso_estensioni_modifica,
        name='estensioni_modifica'),
    url(r'^%s/informa/$' % url_shortcut, v.aspirante_corso_estensioni_informa,
        name='informa'),
]
