# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-08 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0017_auto_20161018_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitocorsobase',
            options={'ordering': ('persona__cognome', 'persona__nome', 'persona__codice_fiscale'), 'permissions': (('view_invitocorsobase', 'Can view invito partecipazione corso base'),), 'verbose_name': 'Invito di partecipazione a corso base', 'verbose_name_plural': 'Inviti di partecipazione a corso base'},
        ),
        migrations.AlterModelOptions(
            name='partecipazionecorsobase',
            options={'ordering': ('persona__cognome', 'persona__nome', 'persona__codice_fiscale'), 'permissions': (('view_partecipazionecorsobarse', 'Can view corso Richiesta di partecipazione'),), 'verbose_name': 'Richiesta di partecipazione', 'verbose_name_plural': 'Richieste di partecipazione'},
        ),
    ]
