# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0019_corsobase_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='op_attivazione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ordinanza presidenziale attivazione'),
        ),
        migrations.AlterField(
            model_name='corsobase',
            name='op_convocazione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ordinanza presidenziale convocazione'),
        ),
    ]
