# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-09 11:21
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models
import django.db.models.deletion
import formazione.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0020_auto_20181107_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorsoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='corsi/', validators=[anagrafica.validators.valida_dimensione_file_8mb, formazione.validators.validate_file_extension], verbose_name='FIle')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formazione.CorsoBase')),
            ],
        ),
        migrations.CreateModel(
            name='CorsoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formazione.CorsoBase')),
            ],
        ),
    ]
