# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0021_corsofile_corsolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormazioneTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome del corso')),
            ],
            options={
                'verbose_name': 'Titolo',
                'verbose_name_plural': 'Titoli',
            },
        ),
        migrations.CreateModel(
            name='FormazioneTitleGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_reference', models.CharField(blank=True, choices=[('1', 'Salute'), ('2', 'Sociale'), ('3', 'Emergenza)'), ('4', 'Advocacy e mediazione umanitaria'), ('5', 'Giovani'), ('5', 'Sviluppo')], max_length=3, null=True, verbose_name='Unità riferimento')),
                ('propedeuticita', models.CharField(blank=True, max_length=255, null=True, verbose_name='Propedeuticità')),
            ],
            options={
                'verbose_name': 'Titolo: Propedeuticità',
                'verbose_name_plural': 'Titoli: Propedeuticità',
            },
        ),
        migrations.CreateModel(
            name='FormazioneTitleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formazione.FormazioneTitleGoal')),
            ],
            options={
                'verbose_name': 'Titolo: Livello',
                'verbose_name_plural': 'Titoli: Livelli',
            },
        ),
        migrations.AddField(
            model_name='formazionetitle',
            name='livello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formazione.FormazioneTitleLevel', verbose_name='Livello'),
        ),
    ]
