# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0022_auto_20181109_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazionetitle',
            name='livello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formazione.FormazioneTitleLevel', verbose_name='Livello'),
        ),
    ]
