# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0049_auto_20181028_1639'),
        ('formazione', '0023_auto_20181109_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorsoEstensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('segmento', models.CharField(blank=True, choices=[('A', 'Tutti gli utenti di Gaia'), ('B', 'Volontari'), ('C', 'Volontari da meno di un anno'), ('D', 'Volontari da più di un anno'), ('E', 'Volontari con meno di 33 anni'), ('F', 'Volontari con 33 anni o più'), ('G', 'Sostenitori CRI'), ('H', 'Aspiranti volontari iscritti a un corso'), ('I', 'Tutti i Presidenti'), ('J', 'Presidenti di Comitati Locali'), ('K', 'Presidenti di Comitati Regionali'), ('L', 'Delegati US'), ('M', 'Delegati Obiettivo I'), ('N', 'Delegati Obiettivo II'), ('O', 'Delegati Obiettivo III'), ('P', 'Delegati Obiettivo IV'), ('Q', 'Delegati Obiettivo V'), ('R', 'Delegati Obiettivo VI'), ('S', 'Referenti di un’Attività di Area I'), ('T', 'Referenti di un’Attività di Area II'), ('U', 'Referenti di un’Attività di Area III'), ('V', 'Referenti di un’Attività di Area IV'), ('W', 'Referenti di un’Attività di Area V'), ('X', 'Referenti di un’Attività di Area VI'), ('Y', 'Delegati Autoparco'), ('Z', 'Delegati Formazione'), ('AA', 'Volontari aventi un dato titolo')], max_length=9)),
                ('sedi_sottostanti', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Estensione del Corso',
                'verbose_name_plural': 'Estensioni del Corso',
            },
        ),
        migrations.AddField(
            model_name='corsobase',
            name='extension_type',
            field=models.CharField(blank=True, choices=[('1', 'Solo su mia sede di appartenenza'), ('2', 'A livello regionale')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corsoestensione',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formazione.CorsoBase'),
        ),
        migrations.AddField(
            model_name='corsoestensione',
            name='sede',
            field=models.ManyToManyField(to='anagrafica.Sede'),
        ),
        migrations.AddField(
            model_name='corsoestensione',
            name='titolo',
            field=models.ManyToManyField(blank=True, to='formazione.FormazioneTitle'),
        ),
    ]
