# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0025_auto_20181114_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formazionetitle',
            name='livello',
        ),
        migrations.RemoveField(
            model_name='formazionetitlelevel',
            name='goal',
        ),
        migrations.AlterField(
            model_name='corsoestensione',
            name='titolo',
            field=models.ManyToManyField(blank=True, to='curriculum.Titolo'),
        ),
        migrations.DeleteModel(
            name='FormazioneTitle',
        ),
        migrations.DeleteModel(
            name='FormazioneTitleGoal',
        ),
        migrations.DeleteModel(
            name='FormazioneTitleLevel',
        ),
    ]
