# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0026_auto_20181119_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='extension_type',
            field=models.CharField(blank=True, choices=[('1', 'Solo su mia sede di appartenenza'), ('2', 'A livello regionale')], default='1', max_length=5, null=True),
        ),
    ]
