# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_auto_20181130_1550'),
        ('formazione', '0029_auto_20181127_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='titolo_cri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Titolo', verbose_name='Titolo CRI'),
        ),
    ]
