# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-28 13:00
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models
import formazione.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0031_corsobase_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='delibera_file',
            field=models.FileField(null=True, upload_to=formazione.validators.delibera_file_upload_path, validators=[anagrafica.validators.ValidateFileSize(3), formazione.validators.validate_file_extension], verbose_name='Delibera'),
        ),
    ]
