# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-08 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0033_auto_20190206_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='tipo',
            field=models.CharField(blank=True, choices=[('BA', 'Corso di Formazione per Volontari CRI'), ('C1', 'Altri Corsi')], max_length=4, verbose_name='Tipo'),
        ),
    ]
