# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0035_auto_20190510_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relazionecorso',
            name='annotazioni_corsisti',
            field=models.TextField(help_text='Annotazioni relative alla partecipazione dei corsisti ', verbose_name='Annotazioni relative alla partecipazione dei corsisti'),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazione_corso', to='formazione.CorsoBase'),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='note_esplicative',
            field=models.TextField(help_text='Note esplicative in relazione ai cambiamenti effettuati rispetto alla programmazione approvata in fase di pianificazione iniziale del corso.', verbose_name='Note esplicative'),
        ),
    ]
