# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0036_auto_20190510_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relazionecorso',
            name='annotazioni_corsisti',
            field=models.TextField(blank=True, help_text='Annotazioni relative alla partecipazione dei corsisti ', null=True, verbose_name='Annotazioni relative alla partecipazione dei corsisti'),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='annotazioni_organizzazione_struttura',
            field=models.TextField(blank=True, help_text="Annotazioni e segnalazioni sull'organizzazione e la logistica e della struttura ospitante il corso", null=True),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='annotazioni_risorse',
            field=models.TextField(blank=True, help_text='Annotazioni relative a risorse e competenze di particolare rilevanza emerse durante il percorso formativo', null=True),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='descrizione_attivita',
            field=models.TextField(blank=True, help_text='Descrizione delle eventuali attività di tirocinio/affiancamento con indicazione dei Tutor', null=True),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='note_esplicative',
            field=models.TextField(blank=True, help_text='Note esplicative in relazione ai cambiamenti effettuati rispetto alla programmazione approvata in fase di pianificazione iniziale del corso.', null=True, verbose_name='Note esplicative'),
        ),
        migrations.AlterField(
            model_name='relazionecorso',
            name='raggiungimento_obiettivi',
            field=models.TextField(blank=True, help_text="Analisi sul raggiungimento degli obiettivi del corso (generali rispetto all'evento e specifici di apprendimento).", null=True, verbose_name='Raggiungimento degli obiettivi del corso'),
        ),
    ]
