# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0038_auto_20190516_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='cdf_area',
            field=models.CharField(blank=True, choices=[('1', 'Salute'), ('2', 'Inclusione Sociale'), ('3', 'Emergenza'), ('4', 'Principi e Valori'), ('5', 'Giovani'), ('6', 'Sviluppo Organizzativo'), ('7', 'Migrazioni'), ('8', 'Cooperazione Internazionale')], max_length=3, null=True),
        ),
    ]
