# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-06 14:29
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0041_corsofile_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsoestensione',
            name='segmento',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VO', 'Volontario'), ('ES', 'Volontario in Estensione'), ('OR', 'Socio Ordinario'), ('SO', 'Sostenitore'), ('DI', 'Dipendente')], max_length=100),
        ),
    ]
