# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0043_auto_20190705_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='data_esame_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seconda data esame'),
        ),
    ]
