# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0046_auto_20190730_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lezionecorsobase',
            options={'ordering': ['inizio', 'scheda_lezione_num'], 'permissions': (('view_lezionecorsobase', 'Can view corso Lezione di Corso Base'),), 'verbose_name': 'Lezione di Corso', 'verbose_name_plural': 'Lezioni di Corsi'},
        ),
        migrations.AddField(
            model_name='lezionecorsobase',
            name='scheda_lezione_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lezionecorsobase',
            name='obiettivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Obiettivo formativo della lezione'),
        ),
    ]
