# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0047_auto_20190805_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezionecorsobase',
            name='lezione_divisa_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formazione.LezioneCorsoBase'),
        ),
    ]
