# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-06 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0048_lezionecorsobase_lezione_divisa_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lezionecorsobase',
            options={'ordering': ['scheda_lezione_num', 'inizio'], 'permissions': (('view_lezionecorsobase', 'Can view corso Lezione di Corso Base'),), 'verbose_name': 'Lezione di Corso', 'verbose_name_plural': 'Lezioni di Corsi'},
        ),
    ]
