# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-04 17:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0049_auto_20190806_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezionecorsobase',
            name='nome',
            field=models.TextField(),
        ),
    ]
