# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-11 10:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0050_auto_20190904_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipazionecorsobase',
            name='eventuale_tirocinio',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], db_index=True, default=None, max_length=1, null=True, verbose_name='Eventuale tirocinio/affiancamento'),
        ),
        migrations.AddField(
            model_name='partecipazionecorsobase',
            name='eventuali_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eventuali Note/Osservazioni'),
        ),
        migrations.AddField(
            model_name='partecipazionecorsobase',
            name='valutazione_complessiva',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valutazione complessiva del Direttore del Corso'),
        ),
        migrations.AddField(
            model_name='partecipazionecorsobase',
            name='valutazione_parte_pratica',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], db_index=True, default=None, max_length=1, null=True, verbose_name='Parte Pratica'),
        ),
        migrations.AddField(
            model_name='partecipazionecorsobase',
            name='valutazione_parte_teorica',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], db_index=True, default=None, max_length=1, null=True, verbose_name='Parte Teorica'),
        ),
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='ammissione',
            field=models.CharField(blank=True, choices=[('AM', 'Ammesso'), ('NA', 'Non Ammesso'), ('AS', 'Assente'), ('MO', 'Assente per motivo giustificato'), ('EN', 'Esame non previsto')], db_index=True, default=None, max_length=2, null=True),
        ),
    ]
