# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-12 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0051_auto_20190911_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='esito_parte_1',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('O', 'Non Previsto')], db_index=True, default=None, help_text='La Croce Rossa.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='esito_parte_2',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('O', 'Non Previsto')], db_index=True, default=None, help_text='Gesti e manovre salvavita.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='eventuale_tirocinio',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('O', 'Non Previsto')], db_index=True, default=None, max_length=1, null=True, verbose_name='Eventuale tirocinio/affiancamento'),
        ),
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='valutazione_parte_pratica',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('O', 'Non Previsto')], db_index=True, default=None, max_length=1, null=True, verbose_name='Parte Pratica'),
        ),
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='valutazione_parte_teorica',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('O', 'Non Previsto')], db_index=True, default=None, max_length=1, null=True, verbose_name='Parte Teorica'),
        ),
    ]
