# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-12 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0052_auto_20190912_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partecipazionecorsobase',
            name='valutazione_parte_pratica',
        ),
        migrations.RemoveField(
            model_name='partecipazionecorsobase',
            name='valutazione_parte_teorica',
        ),
    ]
