# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0054_auto_20190912_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezionecorsobase',
            name='docente_esterno',
            field=models.CharField(blank=True, help_text='Da compilare solo per i docenti esterni', max_length=255, null=True, verbose_name='Docente esterno della lezione'),
        ),
    ]
