# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0057_auto_20190923_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partecipazionecorsobase',
            name='ammissione',
            field=models.CharField(blank=True, choices=[('AM', 'Ammesso'), ('NA', 'Non Ammesso'), ('AS', 'Assente'), ('MO', 'Assente per motivo giustificato'), ('EN', 'Esame non previsto'), ('PA', 'Esame non previsto (partecipante assente)')], db_index=True, default=None, max_length=2, null=True),
        ),
    ]
