# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0058_auto_20191112_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='cdf_area',
            field=models.CharField(blank=True, choices=[('1', 'Salute'), ('9', 'Salute e sicurezza'), ('2', 'Inclusione Sociale'), ('3', 'Emergenza'), ('4', 'Principi e Valori'), ('5', 'Giovani'), ('6', 'Sviluppo Organizzativo'), ('7', 'Migrazioni'), ('8', 'Cooperazione Internazionale')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='corsoestensione',
            name='segmento',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VO', 'Volontario'), ('ES', 'Volontario in Estensione'), ('OR', 'Socio Ordinario'), ('SO', 'Sostenitore'), ('DI', 'Dipendente'), ('VM', 'Operatore Villa Maraini'), ('SC', 'Volontario in servizio civile universale')], max_length=100),
        ),
    ]
