# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0061_auto_20201112_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipazionecorsobase',
            name='partecipazione_online',
            field=models.BooleanField(default=False, verbose_name='Prova pratica su Parte 2 sostituita da colloquio ONLINE'),
        ),
    ]
