# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-09 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0062_merge'),
        ('formazione', '0062_partecipazionecorsobase_partecipazione_online'),
    ]

    operations = [
    ]
