# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-01-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0064_auto_20201214_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='data_esame_pratica',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data esame pratica'),
        ),
    ]
