# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-12 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0064_auto_20201214_1720'),
    ]

    def add_signature_to_old_course(apps, schema_editor):
        CorsoBase = apps.get_model('formazione', 'CorsoBase')

        for corso in CorsoBase.objects.all():
            corso.signature = uuid.uuid4()
            corso.save()

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(add_signature_to_old_course),
    ]
