# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-04-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0066_partecipazionecorsobase_partecipazione_online_da_sostenere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='tipo',
            field=models.CharField(blank=True, choices=[('BA', 'Corso di Formazione per Volontari CRI'), ('BO', 'Corso di Formazione per Volontari CRI Online'), ('C1', 'Altri Corsi'), ('CO', 'Corsi online'), ('CE', 'Corsi equipollenza')], max_length=4, verbose_name='Tipo'),
        ),
    ]
