# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-12 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0065_corsobase_signature'),
        ('formazione', '0066_partecipazionecorsobase_partecipazione_online_da_sostenere'),
    ]

    operations = [
    ]
