# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0069_auto_20201124_1223'),
        ('base', '0025_autorizzazione_mail_verifica'),
        ('formazione', '0066_partecipazionecorsobase_partecipazione_online_da_sostenere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=200)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('comitato_organizzativo', models.ForeignKey(help_text="La Sede organizzatrice dell'Evento.", on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Sede')),
                ('locazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formazione_evento', to='base.Locazione')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
