# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-04 14:00
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models
import formazione.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0067_auto_20210503_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsobase',
            name='delibera_file',
            field=models.FileField(null=True, upload_to=formazione.validators.delibera_file_upload_path, validators=[anagrafica.validators.valida_dimensione_file_6mb, formazione.validators.validate_file_extension], verbose_name='Delibera'),
        ),
    ]
