# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-03 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0067_auto_20210503_1430'),
        ('formazione', '0067_auto_20210413_1434'),
    ]

    operations = [
    ]
