# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-03-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0068_evento_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
