# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-07 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0068_auto_20210504_1400'),
        ('formazione', '0068_merge'),
    ]

    operations = [
    ]
