# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-04-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0070_auto_20210330_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formazione.Evento'),
        ),
    ]
