# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-10 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0069_merge'),
        ('formazione', '0071_corsobase_evento'),
    ]

    operations = [
    ]
