# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-10 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0072_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
    ]
