# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-06-10 12:00
from __future__ import unicode_literals

import anagrafica.validators
from django.db import migrations, models
import django.db.models.deletion
import formazione.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0073_auto_20210510_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=formazione.validators.evento_file_directory_path, validators=[anagrafica.validators.valida_dimensione_file_8mb, formazione.validators.validate_file_extension], verbose_name='File')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formazione.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formazione.Evento')),
            ],
        ),
    ]
