# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-06-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0075_eventofile_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsoestensione',
            name='sedi_sottostanti',
            field=models.BooleanField(db_index=True, default=False, help_text='Flaggare "sedi sottostanti" per rendere visibile il corso a tutti i Comitati/unità territoriali che afferiscono al Comitato organizzatore; qualora non venga messa la spunta, il corso sarà visibile solo alle sedi principali e verranno informati solo i Volontari delle stesse'),
        ),
    ]
