# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0062_auto_20200609_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReperibilitaSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('inizio', models.DateTimeField(db_index=True, verbose_name='Inizio')),
                ('fine', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Fine')),
                ('attivazione', models.TimeField(default='00:15', help_text="Tempo necessario all'attivazione, in formato HH:mm.", verbose_name='Tempo di attivazione')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_reperibilita', to='anagrafica.Persona')),
            ],
            options={
                'permissions': (('view_reperibilita', 'Can view Reperibilità'),),
                'ordering': ['-inizio', '-fine'],
                'verbose_name_plural': 'Reperibilità',
                'verbose_name': 'Reperibilità',
            },
        ),
    ]
