# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_operativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reperibilitaso',
            name='estensione',
            field=models.CharField(choices=[('T', 'Unità Territoriale'), ('L', 'Sede Locale'), ('P', 'Sede Provinciale'), ('R', 'Sede Regionale'), ('N', 'Sede Nazionale')], default='R', max_length=2),
            preserve_default=False,
        ),
    ]
