# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_operativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operazioneso',
            name='funzioni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sala_operativa.FunzioneSO'),
        ),
    ]
