# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0066_auto_20201113_1212'),
        ('sala_operativa', '0002_operazioneso_funzioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operazioneso',
            name='sede',
        ),
        migrations.AddField(
            model_name='operazioneso',
            name='sede',
            field=models.ManyToManyField(blank=True, to='anagrafica.Sede'),
        ),
    ]
