# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-12 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0063_auto_20200611_1351'),
        ('sala_operativa', '0002_reperibilitaso_estensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='reperibilitaso',
            name='creato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Persona'),
        ),
    ]
