# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sala_operativa', '0003_auto_20201113_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeInternazionaleSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operazioneso',
            name='comitato',
            field=models.CharField(blank=True, choices=[('NAZIONALI', 'Nazionali'), ('INTERNAZIONALE', 'Internazionali')], default='NAZIONALI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operazioneso',
            name='sede_internazionale',
            field=models.ManyToManyField(blank=True, to='sala_operativa.SedeInternazionaleSO'),
        ),
    ]
