# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0063_auto_20200611_1351'),
        ('sala_operativa', '0003_reperibilitaso_creato_da'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServizioSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creazione', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_modifica', models.DateTimeField(auto_now=True, db_index=True)),
                ('inizio', models.DateTimeField(db_index=True, verbose_name='Inizio')),
                ('fine', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Fine')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('estensione', models.CharField(blank=True, choices=[('T', 'Unità Territoriale'), ('L', 'Sede Locale'), ('P', 'Sede Provinciale'), ('R', 'Sede Regionale'), ('N', 'Sede Nazionale')], max_length=2, null=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Persona')),
            ],
            options={
                'verbose_name_plural': 'Servizi',
                'verbose_name': 'Servizio',
            },
        ),
    ]
