# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_operativa', '0004_auto_20201113_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioso',
            name='funzione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sala_operativa.FunzioneSO'),
        ),
        migrations.AlterField(
            model_name='operazioneso',
            name='comitato',
            field=models.CharField(blank=True, choices=[('NAZIONALI', 'Nazionali'), ('INTERNAZIONALI', 'Internazionali')], default='NAZIONALI', max_length=50, null=True),
        ),
    ]
