# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_operativa', '0004_servizioso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reperibilitaso',
            name='servizio',
            field=models.ManyToManyField(blank=True, to='sala_operativa.ServizioSO'),
        ),
    ]
