# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_operativa', '0006_auto_20201116_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operazioneso',
            name='funzioni',
        ),
        migrations.AddField(
            model_name='operazioneso',
            name='funzioni',
            field=models.ManyToManyField(blank=True, to='sala_operativa.FunzioneSO'),
        ),
    ]
